- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/templates/admin/delta_change_form.html
- default ordering by date for deltas, apply and export jobs
- add search for deltas, apply and export jobs
- add filter by date for deltas, apply and export jobs
- add child table with deltas when previewing apply jobs
> Add more admin filters and default ordering

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/models.py
Show all user/organization related information in the respective view.
> Another round of admin improvements

- docker-app/requirements.txt
> add deps for docs

- docker-app/Dockerfile
- docker-app/orchestrator/orchestrator.py
- docker-compose.override.local.yml
- Stop the container, sometimes it complains
- Also change the group id for local development
- Less heavy on resources for local development
> Follow up fixes

- docker-app/qfieldcloud/core/serializers.py
QFieldSync fails miserabely to update a project now.
> No longer require owner to be passed when patching

- docker-app/qfieldcloud/core/utils.py
- docker-app/requirements.txt
- docker-compose.override.local.yml
Please review the commits separately.
> Typing and documentation fixes

- docker-app/qfieldcloud/settings.py
There was a mysterious deletion of some of the invitations. Turns out it was this cron.
> Keep the expired invitations

- docker-app/qfieldcloud/core/invitations_utils.py
- docker-app/qfieldcloud/core/management/commands/inviteusers.py
```
python manage.py createuser --username=user1 --emails=test1@test.com test2@test.com --exit-on-failure
```
> Add `inviteusers` script to invite multiple users at once

- docker-app/qfieldcloud/core/admin.py
- docker-app/worker_wrapper/wrapper.py
Also:
- Fix mass updating delta status from admin
> Add after_docker_exception, so now failed delta_apply also updated the delta status

- .env.example
- conf/nginx/templates/default.conf.template
- docker-compose.override.local.yml
However, downloading is still not working, but the access to the console is there. The proxy download will be fixed when we really start using minio for other than tests.
> Fix minio in the new nginx setup

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/settings.py
Well, it's funny I was so focused on the migrations I forgot to update the model itself.
> Fix admin saving deltas

- docker-app/qfieldcloud/settings.py
> [Backport release] No expiration for invitations

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/utils.py
- docker-app/qfieldcloud/core/utils2/audit.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/settings.py
- docker-app/requirements.txt
Log actions such as modifications of Django models, uploading, downloading files etc.
> Audit the important user actions

- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/tests/test_delta.py
- docker-app/qfieldcloud/core/tests/test_qfield_file.py
- docker-app/qfieldcloud/core/views/package_views.py
- docker-app/qfieldcloud/core/views/qfield_files_views.py
- docker-app/worker_wrapper/wrapper.py
- docker-qgis/entrypoint.py
- docker-qgis/utils.py
- a more refined workflow definition and validation
- versioned workflow output
- less settings to define a workflow step - less confusion
- a new "output" key in the root feedback object to avoid using arr indices
- better feedback when some tests are failing
Fixes https://github.com/opengisch/qfieldcloud/issues/60
> Improvements on the job execution inside the QGIS container

- README.md
- conf/nginx/templates/default.conf.template
- docker-app/qfieldcloud/core/tests/test_delta.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-compose.override.local.yml
- docker-compose.yml
A huge improvement on consuming the API. However, the django API get's more tightly coupled with nginx now.
> Download files using nginx x-accel-redirect, so the s3 redirect happens withing nginx

- docker-app/qfieldcloud/core/migrations/0051_auto_20211125_0444.py
@robert197 I think this was the issue you had. Found it on sentry.
> Fix migrations on deltas for 3d geometry

- docker-app/qfieldcloud/core/management/commands/inviteusers.py
- docker-app/qfieldcloud/settings.py
> [Backport release] Add limit argument how many users should be invited per run

- docker-app/qfieldcloud/core/models.py
> Fix unable to add the owner of an organization to a team

- docker-app/qfieldcloud/core/exceptions.py
- docker-app/qfieldcloud/core/tests/test_delta.py
- docker-app/qfieldcloud/core/views/deltas_views.py
> [Backport release] Ignore newcoming deltas with the duplicate id

- .github/workflows/test.yml
- .pre-commit-config.yaml
as this script isn't cross platform
(will push temporary commits shortly to ensure the check works)
> [precommit] move check_envvars hook to CI

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_packages.py
- docker-app/worker_wrapper/wrapper.py
- docker-qgis/utils.py
Will also add tests so it never happens again.
> Fix needs_repackaging check, last_packaged < last_updated => need repackaging

- docker-app/qfieldcloud/settings.py
> Reenable logs (e.g. when server error occurred)

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/rest_utils.py
- docker-app/qfieldcloud/core/tests/test_delta.py
- docker-app/qfieldcloud/core/tests/test_packages.py
- docker-app/qfieldcloud/core/tests/test_qgis_file.py
- docker-app/qfieldcloud/core/urls.py
- docker-app/qfieldcloud/core/utils2/__init__.py
- docker-app/qfieldcloud/core/utils2/jobs.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/core/views/package_views.py
- docker-app/qfieldcloud/settings.py
- docker-app/qfieldcloud/testing.py
So no longer weird redirect cases for any type of files in QFC.
> Make /package/latest/file responses use nginx X-Accel-Redirect instead of HTTP redirect

- docker-app/qfieldcloud/core/tests/test_delta.py
- docker-app/qfieldcloud/core/tests/test_geodb.py
- docker-app/qfieldcloud/core/tests/test_organization.py
- docker-app/qfieldcloud/core/tests/test_packages.py
- docker-app/qfieldcloud/core/tests/test_permission.py
- docker-app/qfieldcloud/core/tests/test_project.py
- docker-app/qfieldcloud/core/tests/test_qfield_file.py
- docker-app/qfieldcloud/core/tests/test_qgis_file.py
- docker-app/qfieldcloud/core/tests/test_queryset.py
- docker-app/qfieldcloud/core/tests/test_user.py
(didn't run the tests yet, let's see if they really are useless)
> remove useless tearDown methods

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/tests/test_packages.py
- docker-app/qfieldcloud/core/utils.py
- docker-app/qfieldcloud/core/views/package_views.py
- docker-app/qfieldcloud/core/views/qfield_files_views.py
- docker-app/worker_wrapper/wrapper.py
- docker-qgis/Dockerfile
- docker-qgis/entrypoint.py
- docker-qgis/process_projectfile.py
- docker-qgis/requirements.txt
- docker-qgis/utils.py
- Bump QGIS version to the latest patch 3.22.3
- One step closer to md5 instead of sha256
- Extra logs when downloading/uploading files in jobs
- Print project layer checks for process_projectfile job
- Admin improvements: more fields for projects
- Make `layers` from packages/qfield_fiels/package the same format as in process_projectfile view.
> Various packaging and jobs improvements

- conf/nginx/templates/default.conf.template
> Remove no longer used minio endpoint

- docker-app/qfieldcloud/settings.py
> No need to have an invitation to register

- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/core/views/files_views.py
- No need to check for authentication since the files should be public s3
- Make sure the files can be served with X-Accel-Redirect on prod
- Return absolute avatar URL
> s3 file links fixes

- conf/nginx/templates/default.conf.template
- docker-app/qfieldcloud/core/models.py
tried my best to keep a single definition of the proxy, failed. Better be like this.
> Add access-control-allow-origin header for /swagger.yml

- docker-app/worker_wrapper/wrapper.py
> Add explicit message about timeout errors in the logs

- docker-app/qfieldcloud/core/tests/test_qgis_file.py
- docker-app/qfieldcloud/core/views/files_views.py
Fix https://github.com/opengisch/qfieldcloud/issues/299#issuecomment-1070769037
> Prevent starting a new job on file uploads if there is already pending one

- docker-app/qfieldcloud/core/tests/test_qgis_file.py
- docker-app/qfieldcloud/core/views/files_views.py
> [Backport release] Prevent starting a new job on file uploads if there is already pending one

- docker-app/qfieldcloud/core/migrations/0051_auto_20211125_0444.py
> [Backport release] Fix core_delta_geom_trigger_func to work with nan measurements

- docker-app/qfieldcloud/core/models.py
> [Backport release] Fix the Delta.Method enums to inherit str, so the string comparison works

- docker-app/qfieldcloud/core/models.py
Fix https://github.com/opengisch/qfieldcloud/issues/313
> Add fallback_output to the jobs model

- docker-app/qfieldcloud/core/tests/test_delta.py
> testing: don't hardcode project uuid to avoid s3 side effects

- docker-app/qfieldcloud/settings.py
- docker-app/qfieldcloud/urls.py
- docker-app/requirements.txt
- docker-compose.override.local.yml
Ignore, it will be merged with https://github.com/opengisch/qfieldcloud/commit/aa010f193dd7402546351919bea22b34f543cbe1 #330
> Added debug toolbar for local development

- docker-app/qfieldcloud/core/admin.py
> Show project_filename field in Project admin

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/templates/admin/project_files_widget.html
- docker-app/qfieldcloud/core/utils.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/settings.py
- docker-app/qfieldcloud/subscription/tests/test_storage_quota.py
- docker-app/qfieldcloud/urls.py
Also added unified place to delete files and versions with auditing and project update.
> Add project files widget to list and delete files and versions

- docker-app/qfieldcloud/core/migrations/0055_auto_20220204_1654.py
- docker-app/qfieldcloud/core/migrations/0056_projectpermissionsview.py
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/sql_config.py
- docker-app/qfieldcloud/core/tests/test_user.py
- docker-app/qfieldcloud/core/views/users_views.py
> Optimize getting organization permissions query with a view

- docker-app/qfieldcloud/core/admin.py
- docker-app/worker_wrapper/wrapper.py
- docker-compose.override.local.yml
Race conditions:
:car: 
:steam_locomotive:
> Fix updating project thumbnail rewriting the Project.project_filename field to null

- docker-app/qfieldcloud/core/migrations/0057_auto_20220701_2140.py
- docker-app/qfieldcloud/core/sql_config.py
- docker-app/qfieldcloud/core/tests/test_user.py
No worries I modified an existing migration, I already patched the DB in
a compatible way
> Make emails unique among regular users

- docker-qgis/apply_deltas.py
- docker-qgis/entrypoint.py
- docker-qgis/process_projectfile.py
- docker-qgis/utils.py
- Add timestamp in the logs
- Filter out sensitive information such as passwords
- Log information about project files
> Improvements on logging in the QGIS container

- .env.example
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/settings.py
- docker-compose.override.dev.yml
- docker-compose.override.local.yml
- docker-compose.override.test.yml
- docker-compose.yml
This has been done manually so far. Now we are reboot proof.
Fix issues reported https://github.com/opengisch/QField/discussions/3615 .
> Automatically scale worker_wrapper on startup

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/permissions_utils.py
- docker-app/qfieldcloud/core/tests/test_queryset.py
- docker-app/qfieldcloud/subscription/tests/test_organization.py
Save some extra queries and save a few tens of milliseconds.
> Optimizations on organization querysets

- .github/workflows/test.yml
- docker-app/qfieldcloud/authentication/admin.py
- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/tests/test_admin.py
- docker-app/qfieldcloud/notifs/admin.py
Also fix a few problematic admin pages
> Improve speed, consistency and general UX in admin

- .env.example
- .github/disabled-workflows/deploy_dev.yml
- .github/workflows/backport.yml
- .github/workflows/build_and_push.yml
- .github/workflows/release_drafter.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
- README.md
- docker-compose.yml
- scripts/check_envvars.sh
- scripts/init_letsencrypt.sh
- Configure CONF_PATH from the .env file, without modifying the script files
- `docker-compose` is dead, long live `docker compose`
- Bump all workflows to ubuntu 22.04
> Sys admin improvements 

- .env.example
- README.md
- docker-app/qfieldcloud/settings.py
- docker-app/requirements.txt
- docker-compose.override.local.yml
- docker-compose.yml
Also do not expose Redis port by default.
> Setup a constance cache with memcached

- conf/nginx/templates/default.conf.template
- docker-app/Dockerfile
- docker-app/qfieldcloud/core/logging/formatters.py
- docker-app/qfieldcloud/settings.py
- Add logger source the JSON of the django app
- Remove the whitespace after the ":" in the JSON in the logs
- Fix missing timestamps
- Add the request ID in the NGINX logs
> Some logger improvements

- docker-app/requirements.txt
> Bump few dependencies from JazzBand

- scripts/debug.sql
Would be very nice to see the subscription plan of the customer again in a future fix.
> Temporary fix for debug queries by fixing renamed fields and hiding the subscription plan.

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/utils2/projects.py
The only question is why we see this now...
> Allow also teams as project collaborators when project is within organization

- docker-app/qfieldcloud/core/tests/test_qgis_file.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/settings.py
- docker-app/qfieldcloud/subscription/tests/test_package.py
This reverts commit 359e048a5ce92cac2e9fff901fda1293e381deac.
> Revert "Temporary disable non required deletions"

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_organization.py
This is super important for billing.
> Do not account staff users as active users

- docker-app/Dockerfile
- docker-app/qfieldcloud/settings.py
- docker-app/requirements.txt
Especially useful is the `shell_plus` script. Also add graphviz for building documentation easily in the future.
> Added django-extensions dependency to make life sweet

- .gitignore
This occurs on prod and dev environments.
> Ignore certbot created files

- docker-compose.yml
relates to https://github.com/opengisch/qfieldcloud-private/pull/354
> Add docker compose app depends_on

- .github/workflows/release_drafter.yml
> Link release_drafter to release branch

- .github/workflows/test.yml
- .gitignore
- Only run tests on `master`, `release` and `pull_request`
- Add `*.orig` to `.gitignore` (leftovers from conflicts)
> Tiny git workflow improvements

- .env.example
- docker-app/qfieldcloud/urls.py
> Make the root of QFieldCloud redirect to admin page and doc some envvars

- .gitmodules
> Remove bootstrap submodule as it is no longer needed

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/paginators.py
- docker-app/qfieldcloud/settings.py
Speed up django admin interface for large lists
> Qf 2598 django admin speed

- docker-app/Dockerfile
- docker-app/qfieldcloud/settings.py
Does not cause any harm if configured.
> Configure locales and languages

- .env.example
- docker-compose.yml
> Set SENTRY_RELEASE

- docker-app/qfieldcloud/core/management/commands/dequeue.py
> Qf 2641 code style improvements

- docker-app/requirements.txt
Changelog:
https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-2
> Bump `jinja` from `3.0.3` to `3.1.2`

- docker-app/requirements.txt
Check each commit for more info.
> Bump a batch of patch versions for dependencies

- docker-app/requirements.txt
Part of the overall effort to bring the dependencies to more current version, partly in the hope that some mysterious bugs get solved.
Check each commit message for details.
Follow-up of https://github.com/opengisch/qfieldcloud/pull/623. There will be 1 or 2 more PRs like this.
> Bump various deps

- docker-app/qfieldcloud/core/tests/test_packages.py
It did not fix. But think could still add this?
> Speed (and stabilize?) up test_packages

- docker-app/qfieldcloud/settings.py
- docker-qgis/apply_deltas.py
See individual commit messages for reasoning in case of doubt
> A bit more type safety here and there

- docker-qgis/entrypoint.py
~Depends on https://github.com/opengisch/libqfieldsync/pull/46~
> Less crs conversions

- .mypy.ini
- .pre-commit-config.yaml
- docker-qgis/apply_deltas.py
Depends on https://github.com/opengisch/libqfieldsync/pull/48/files?w=1
Missing bits:
```
docker-qgis/apply_deltas.py:953: error: Missing positional argument "client_pks" in call to "patch_feature"  [call-arg]
docker-qgis/apply_deltas.py:955: error: Missing positional argument "client_pks" in call to "delete_feature"  [call-arg]
```
@suricactus any idea?
> Enable mypy for docker-qgis

- docker-app/qfieldcloud/core/models.py
Consider taking over some of the suggested style / readability improvements, if they do not break tests.
> [WIP] Suggest common base methods for active users methods

- docker-app/qfieldcloud/core/templates/admin/project_files_widget.html
> QF-2744 Quickfix Admin Projects download latest version button

- README.md
Feel free to add some feedback.
> Add a rule about commits testability in PRs

- docker-app/qfieldcloud/core/pagination.py
- docker-app/qfieldcloud/core/paginators.py
- docker-app/qfieldcloud/core/tests/test_api.py
- docker-app/qfieldcloud/core/views/projects_views.py
> Paginator for Projects as PoC

- docker-app/qfieldcloud/core/pagination.py
- docker-app/qfieldcloud/core/paginators.py
- docker-app/qfieldcloud/core/tests/test_api.py
- docker-app/qfieldcloud/core/views/projects_views.py
- docker-app/qfieldcloud/settings.py
> Customize Model-level Pagination 

- docker-app/qfieldcloud/core/tests/test_qgis_file.py
- docker-app/qfieldcloud/core/views/files_views.py
The slowness is added by the line calling `version.head()`, which is additional HEAD request to S3 for each and every version. Far from optimal...
Some clients (e.g. QField, QFieldSync) are still requiring the `sha256` key to check whether the files needs to be reuploaded. Since we do not have control on these old client versions, we need to keep the API backward compatible for some time and assume `skip_metadata=0` by default.
TODO
Follow up PR that uses the `get_project_file_versions`, instead of custom implementation of it in `files_views.py`.
> Skip downloading the S3 metadata if `skip_metadata` is passed to the API `/files/` list endpoint

- docker-app/qfieldcloud/core/admin.py
|---|---|
| ![image](https://github.com/opengisch/qfieldcloud/assets/2820439/eb4cca1f-3a8f-4a16-86ad-4c913317356e) | ![image](https://github.com/opengisch/qfieldcloud/assets/2820439/bab130de-ab89-4312-b85f-834839d429f7) |
> [admin] Be more explicit the numbers mean in storage filed in Person/Org admin

- docker-app/worker_wrapper/wrapper.py
@faebin was right, no idea what I was testing and why it worked. Most probably I didn't have another compose running in the background.
Follow-up of #716
> Seems searching for multiple labels do not work

- docker-app/qfieldcloud/core/models.py
While not the best thing I have created in my life, I think for now it can serve the role of listing all problems that we know at QFieldCloud and already show them to the end user.
> Added `Project.problems` to list failing requirements for the project file

- docker-app/qfieldcloud/core/models.py
Fixing "OpenStreetMap does not have a PK".
> Do not check for PK of project layers if not a vector layer

- docker-app/qfieldcloud/core/pagination.py
- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/views/deltas_views.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/core/views/jobs_views.py
- docker-app/qfieldcloud/core/views/package_views.py
- docker-app/qfieldcloud/core/views/projects_views.py
- docker-app/qfieldcloud/core/views/qfield_files_views.py
> Make OpenAPI docs more up to date, document wrong and hidden request and response params

- .github/workflows/build_and_push.yml
- .github/workflows/test.yml
> Bump ci and avoid node 12 deprecation

- docker-app/qfieldcloud/core/models.py
> Cannot add organization owner as collaborator to project

- docker-app/qfieldcloud/core/utils2/storage.py
See https://app.clickup.com/t/866av28j2
> When project is deleted, it's files are not permanently deleted

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/templates/admin/core/job/change_form.html
- docker-app/qfieldcloud/core/utils2/delta_utils.py
- docker-app/worker_wrapper/wrapper.py
> Add a way to easily export deltafiles from Django Admin - Deltas list and Job view

- docker-app/qfieldcloud/core/models.py
- docker-qgis/process_projectfile.py
- docker-qgis/utils.py
…fix through not re-enconding file's contents.
This will almost certainly _not_ be enough to fix the issue, but it can improve on the situation because it avoids one decoding ("fromstring"). To fix the issue I need to identity the source of the "corruption".
> Improving project file validation user experience

- .github/workflows/test.yml
Did not delete it in case it is really needed by someone
> Disable tmate sessions

- docker-qgis/entrypoint.py
- docker-qgis/utils.py
See https://github.com/opengisch/libqfieldsync/pull/56
> Actually set the bad layer handler on project to support localized datapath layer packaging

- docker-app/qfieldcloud/core/admin.py
> Add Django Project Admin configuration of the file versions to be stored

- docker-app/qfieldcloud/subscription/admin.py
> Add subscription admin

- docker-app/qfieldcloud/subscription/models.py
Fix for https://github.com/opengisch/QFieldCloud-on-prem/issues/15.
> Make AbstractSubscription.__str__() harmless

- .env.example
- docker-compose.override.local.yml
- docker-compose.override.test.yml
> Chore cleanup compose and env

- docker-app/worker_wrapper/wrapper.py
Think we have no more redis anywhere ?
> Remove redis related stuff

- docker-app/qfieldcloud/subscription/admin.py
> QF-3715 In Subscriptions admin add a filter by plan

- docker-app/qfieldcloud/subscription/admin.py
Create:
Update:
Before when creating one cannot select their plan.
> Restored the ability to create subscriptions with plans

- docker-compose.yml
- docker-qgis/Dockerfile
> Switch from `qgis/qgis` image to simple Ubuntu with apt-installed qgis

- docker-qgis/Dockerfile
- docker-qgis/entrypoint.py
- docker-qgis/qfc_worker/process_projectfile.py
- docker-qgis/qfc_worker/utils.py
Check the commit messages for more info.
> Force garbage collection of all dangling QGIS objects around

- docker-app/qfieldcloud/subscription/admin.py
|-|-|
| ![image](https://github.com/opengisch/qfieldcloud/assets/2820439/88052fc9-4ea2-4749-bff7-c8945b12e735) | ![image](https://github.com/opengisch/qfieldcloud/assets/2820439/c00b473b-972b-440d-8ccd-30cc5d6d629a) |
> Added a way to configure the subscription status in the Admin

- docker-app/qfieldcloud/core/templates/admin/project_files_widget.html
> Fixed missing button styles for project admin "refresh files list" 

- docker-qgis/requirements.txt
Prevents re-uploading of 8+MB files when they have not changed at all
Fix https://github.com/opengisch/QField/issues/5148#issuecomment-2090307608 and https://github.com/opengisch/QField/issues/5237#issuecomment-2111695728
> Bump QFieldCloud SDK to 0.8.4

- docker-qgis/requirements_libqfieldsync.txt
Catch https://github.com/opengisch/libqfieldsync/pull/82
> Update libqfieldsync revision to catch project plugins support

- docker-app/qfieldcloud/core/admin.py
Fixture for already merged #939
> Secret admin: Use @admin.display desc for SecretAdmin.created_by__link

- docker-app/requirements_test.txt
> Bump to latest version in the testing framework, hoping that everything autofixes

- .flake8
- .pre-commit-config.yaml
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/permissions_utils.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/subscription/models.py
- ruff.toml
> Switch to ruff instead of black, isort, flake8 and autoflake

- README.md
As they highlighted here, we never promoted our ideas platform. https://github.com/opengisch/QField/discussions/5393#discussioncomment-9878195
> Update README.md with more support options

- README.md
- scripts/debug.sql
Will be merged by start of July.
> Rename "qfieldcloud" to "QFieldCloud"

- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
> Bump some deps to more recent versions

- README.md
- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
- docker-compose.override.local.yml
Check individual commit messages.
> Bump various dependencies 

- .pre-commit-config.yaml
- docker-app/qfieldcloud/authentication/authentication.py
- docker-app/qfieldcloud/authentication/tests/test_authentication.py
- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/settings.py
- docker-app/qfieldcloud/urls.py
- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
It's final time, as 3.2 is end of life for a few months already.
> Bump to Django 4.2

- docker-app/qfieldcloud/core/admin.py
|-|-|
| ![image](https://github.com/user-attachments/assets/94c37d8b-476c-4b05-9eb6-ae8033fe1dd6) | ![image](https://github.com/user-attachments/assets/ee6f5487-ecfe-4095-ac51-124ca2cd1ab0) |
Fixes #1023
> Expose "overwrite_conflicts" Project flag in the admin

- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
Check the individual commit messages for more info.
> Bump deps waiting on django 4.2

- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
Check individual commits for changelog and diffs. Nothing breaking, but some security patched.
> Bump various dependencies

- docker-app/requirements/requirements.in
Does not bring any functional value, besides developer experience.
> [chore] Sort dependencies alphabetically

- docker-app/qfieldcloud/core/fields.py
- docker-app/qfieldcloud/core/migrations/0081_file_storage_project_and_more.py
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/filestorage/urls.py
- docker-app/qfieldcloud/filestorage/views.py
- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
Migrate the avatars to the new storage too.
> Migrate avatar storage using django-storages instead of raw s3 queries

- docker-compose.override.local.yml
@suricactus I didnt test but am just quite sure should be fixed?
> Fix typo in docker-compose.override.local.yml

- docker-app/qfieldcloud/filestorage/management/commands/migrateavatars.py
This script should ideally be ran only once.
> Migrate avatars from the old storage to the new storage

- docker-app/qfieldcloud/core/tests/test_packages.py
- docker-app/qfieldcloud/core/views/package_views.py
This PR make last package view also provide the attachments files.
> Attach project files also in last package view

- docker-app/qfieldcloud/filestorage/management/commands/migrateavatars.py
For instances with thousands of users it makes a difference.
> Prioritize the most recently active users to be migrated first in `migrateavatar`

- docker-app/qfieldcloud/filestorage/views.py
Most probably we want to make the hardcoded `"logo.svg"` to be a configuration in the future. For now I believe it is good enough.
> Fallback to the legacy avatar if an avatar is not migrated yet, or serve static file if avatar is not available at all

- docker-app/qfieldcloud/core/views/package_views.py
- docker-app/qfieldcloud/filestorage/models.py
- docker-app/qfieldcloud/filestorage/view_helpers.py
This reverts commit 1b6434ec5cc5fc081060255ce1a3dd569fcc4e88, reversing changes made to 0e7c0f82c5662cf2b83a757c001cb9d620d65776.
> Revert "Merge pull request #1183 from opengisch/QF-5531-fix-download-latest-package"

- docker-app/qfieldcloud/core/cron.py
This PR fixes an AttributeError reported in #1190 
Closes #1190
> Fix AttributeError: ''DeleteObsoleteProjectPackagesJob'' object has no attribute ''job''

- docker-app/qfieldcloud/core/staticfiles/css/sso.css
- docker-app/qfieldcloud/core/templates/allauth/elements/provider.html
No UI change, just css & style refactoring, with a defensive approach and default values. So in case the style color value gets somehow absurd, the default value is applied.
> Refactor styling for social login providers buttons

- docker-app/qfieldcloud/core/views/redirect_views.py
- docker-app/qfieldcloud/urls.py
> Redirect QFieldSync project URL to the admin view

- docker-app/qfieldcloud/core/models.py
Basically the title. Do not expect a QGS file in the localized project.
> Skip missing project file problem for localized datasets project

- docker-app/qfieldcloud/subscription/models.py
This PR adds `get_plans_for_user(...)` into the `Plan` base model and adds the `is_frontend_user_editable = False` flag to `AbstractSubscription` so that by default subscriptions are considered not editable in the web UI.
> Refactor subscription base model: extract plan lookup and add frontend-editable flag

- docker-app/qfieldcloud/filestorage/tests/test_attachments.py
No much more things than the title. I guess such a test was missing.
> test(attachments): add test to check attachment & package storage

- docker-app/qfieldcloud/core/models.py
This PR intends to ensure that a Secret having the `assigned_to` field of type Person set :
- is a member of the Organization, in case the Secret is for an Organization.
- is a collaborator of the Project, in case the Secret is for a Project.
> check(secrets): ensure an assigned_to user is org's member or project's collaborator

- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/tests/test_project.py
> fix(packaging): handle `needs_repackaging` on project API

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_packages.py
This PR ensures that the repackaging of projects is triggered for users and collaborators, when some User-level secrets are assigned.
> test(package): ensure repackaging is needed with secrets

- docker-app/qfieldcloud/filestorage/utils.py
Caught by our new code reviewer @beanzmo :)
> doc: better documentation of `is_admin_restricted_file`

- docker-qgis/Dockerfile
Because 3.44 has nice features I don't want QFieldCloud to kill ;)
> Update QGIS to 3.44.1

- docker-app/qfieldcloud/core/models.py
This PR intends to make API calls to the Projects API faster, with an optimization of the ORM logic behind the Projects' `latest_package_job_for_user`.
> refactor(package): revamp ORM logic behind Project's `latest_package_job_for_user`

- docker-app/worker_wrapper/wrapper.py
We don't want to miss Org-level Secrets in the worker.
> fix(secrets): make worker get a query set with all secrets

- docker-app/qfieldcloud/core/tests/test_secret_packages.py
Follow-up of #1299 with a test case.
> test(secret): ensure the worker is retrieving Org-level secrets

- docker-app/qfieldcloud/core/models.py
I guess here we overlooked a test. Such changes should be done with greater care.
> fix: be explicit that the given assert is disabled on prod environment

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_secret.py
> fix: secrets filtering for projects owned by non-organizations

- docker-app/requirements/requirements_test.in
- docker-app/requirements/requirements_test.txt
- docker-app/requirements/requirements_worker_wrapper.in
- docker-app/requirements/requirements_worker_wrapper.txt
Changes: https://github.com/jd/tenacity@8.3.0...9.1.2
> Bump various test dependencies

- docker-app/requirements/requirements.txt
- docker-app/requirements/requirements_runtime.txt
- docker-app/requirements/requirements_test.txt
- docker-app/requirements/requirements_worker_wrapper.txt
> chore(deps): Bump all indirect dependencies to their latest version

- docker-qgis/requirements.in
- docker-qgis/requirements.txt
See individual commits for more info.
> Bump and pin deps in the qgis worker container

- docker-app/qfieldcloud/filestorage/management/commands/migratefilestorage.py
- docker-app/qfieldcloud/filestorage/migrate_project_storage.py
This PR intends to make the filestorage migration command run through all the filtered projects, by catching exceptions so that the command can be monitored.
ping @toebivankenoebi
> edit(fs migration): update command error handling

- README.md
This is related to the overall improvement of the README file. Note this PR could be merged ignoring some upcoming documentation improvements about testing.
> docs: add docs about dump restore, improve the instance launch, add info how to access the database

- docker-app/qfieldcloud/filestorage/management/commands/migratefilestorage.py
Nothing more than the title, follow-up of #1336
> edit(migration): remove prompt if accept argument is set

- .pre-commit-config.yaml
- .vscode/launch.json
- README.md
The debugger attaches to already running docker compose stack.
> chore: add debugger config for vscode and update README.md

- docker-app/qfieldcloud/filestorage/management/commands/migratefilestorage.py
- docker-app/qfieldcloud/filestorage/migrate_project_storage.py
This PR intends to make the migration command use harmonized logging for everything that needs to be logged during one run.
> edit(fs migration): use harmonised logger during fs migration

- docker-app/requirements/requirements.in
> Bump Python dependencies
