opengisch/QFieldCloud

- .github/workflows/build.yml
The goal of this PR is to build the public containers and push to public registry.
We will use the public application container as a base for our private containers.
In order to make it work completely we need to set following secrets inside the github secrets settings:
- DOCKER_HUB_USERNAME
- DOCKER_HUB_ACCESS_TOKEN
> Change github workflow to push containers to public registry

- docker-compose.yml
So that we don't need to manually setup cronjobs on the host (easier to inspect, easier to deploy, easier to test)
> run crons inside docker

- docker-app/qfieldcloud/core/admin.py
Fix:
```
Cannot resolve keyword 'team_organization' into field. Choices are: auth_token, date_joined, email, emailaddress, first_name, geodb, groups, has_accepted_tos, has_newsletter_subscription, id, invitation, is_active, is_staff, is_superuser, job, last_login, last_name, logentry, organization, organizationmember, owner, password, projectcollaborator, projects, remaining_invitations, socialaccount, team, teammember, uploaded_deltas, user_permissions, user_type, useraccount, username
```
> Fix exception thrown when searching for user

- docker-app/worker_wrapper/wrapper.py
We need to copy the command before appending to it, because it comes as static and is appended multiple times
> Run the worker `apply_delta` without `--overwrite-conflicts`

- docker-app/qfieldcloud/core/permissions_utils.py
Added user_has_organization_role_origins and fix can_become_member to use role_origins
Forbid becoming a collaborator when owner, collaborator or organization owner only
> Permission fixes when adding collaborators

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/utils.py
There was an extra HEAD operation for each iteration, which proved to be quite slow. Now all happens in a single (well, maybe a few since it's 1000 objects per request) request.
> Faster list files using list_objects and list_object_versions

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_queryset.py
This is the opposite of the already existing `Project.objects.for_user()`, now we add `User.objects.for_project`. It will return all the users that are somehow involved in the project: as project owner, organization owner, organiaztion admin, collaborator, member of a collaborating team. Note for a public project it will not return all the users.
Probably it is worth adding the users that have contributed in the past, but no longer are part of the project. Situation:
- `suricactus` owns a public project `OpenKebabMap`
- `suricactus` adds a few changes in the project via qfield
- `suricactus` becomes a vegan and transfers it to `kebab_destroyer_97`
- `suricactus` is no longer available in the people who contributed in the project
Easy to achive by looking in the …
> Get all the users involved into a project with their roles and role origins

- docker-app/qfieldcloud/core/admin.py
- Don't add geodb by default when creating a new user from admin
- Add user accounts by default when creating a new user from admin
- Add search field in the project admin page
- Simplify creation of users, organization and teams in admin
> Admin improvements

- docker-app/qfieldcloud/core/querysets_utils.py
- docker-app/qfieldcloud/core/tests/test_queryset.py
Avoid situations like this when teams from other organizations are suggested:
> Only suggest teams that are part of the project-owning organization

- scripts/check_envvars.sh
Now it is expected that the system python already has it. It is not always the case.
> Make sure pyyaml is installed dependency

- docker-compose.yml
Way too small for the bulk data that is printed. However, the spam from `GET /deltas/<project_id>` is way too big too. We should limit what is printed as response body to 10k.
> Increase logs stored for app

- .github/workflows/test.yml
- .pre-commit-config.yaml
- docker-app/qfieldcloud/core/management/commands/dequeue.py
This PR fixes failing false alarm with breaking tests due to cached content type ids.
The worker wrapper caches outdated ContentType ids during tests since it runs in a separate container than the tests, which then the tests.
> Fix failing tests introduced with #202

- .env.example
This will fix the "invalid sslmode value" error, when following the documentation mentioned in #211 
Docker doesn't support inline comments in `.env` files: https://docs.docker.com/compose/env-file/
> Update .env.example to fix 'invalid sslmode value'

- docker-compose.override.local.yml
This will fix a syntax error in `docker-compose.override.local.yml` mentioned in #211 
Referring to the documentation, the depends_on condition is not supported anymore in docker-compose 3.x.
I cannot estimate if there are any side effects by removing this, but i don't think so.
> Fix docker-compose.override.local.yml Syntax Error

- conf/nginx/templates/default.conf.template
nginx has a default timeout of 60 seconds. No more. Fix #68
> Increase timeouts when uploading huge files

- docker-app/qfieldcloud/core/exceptions.py
- docker-app/qfieldcloud/core/tests/test_delta.py
- docker-app/qfieldcloud/core/views/deltas_views.py
Proved to be very quirky to manage this from QField side. Therefore, just ignore the new comming delta with the same id, instead of throwing an error.
> Ignore newcoming deltas with the same id

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/utils.py
I don't think this exactly matches what's used on disk (probably only stores changed chunks ?), because it just sums the size of all versions. I didn't find actual data usage exposed. 
Seems AWS has an API to calculate actual size per prefix (see https://stackoverflow.com/a/35095500/13690651), but didn't find anything like that with boto3...
Still, I think it makes sense to simply sum the versions, as it's easier to understand for users anyway.
Some questions:
- Currently, `Project.storage_size()` will result on API calls each time it is invoked, meaning that it's not really usable for anything else than displaying one at a time in the admin (which is the only usage of it currently as far as I can see). I guess we need to persist that in the database. But then when exactly do we update it …
> Fix storage size calculation to include old versions

- docker-app/qfieldcloud/core/cron.py
- docker-app/qfieldcloud/core/management/commands/purge_old_file_versions.py
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_qgis_file.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/core/views/files_views.py
This adds:
- a management command to purge old versions of files (`purge_old_file_versions`)
- a cronjob running this command once a day
It currently hardcodes the number of versions to keep (3 for COMMUNITY accounts, 10 for PRO accounts).
Some questions / things to consider:
- Using a number of versions to keep instead of a time span means that quickly pushing many changes is less safe than rarely pushing, which IMO is not nice for the user
- The command runs on all projects at once. Hard to predict how slow this will be in real life. We probably need to batch the queries somehow ? Do we have a way to test this without affecting actual data ?
- Unsure if a management command is the right place for this ? Other such tasks are directly implement in cron.py, maybe that's enough ?
- Do we …
> Purge old versions of project files

- docker-app/qfieldcloud/core/utils.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/core/views/files_views.py
I have used the name "delete" as it is more straigh forward for me what it means. I guess the function you have recently added should be renamed too.
Ideally `purge_old_file_versions` should start using `delete_file_version`.
> Added delete_file_version function to deletes a specific file version

- docker-app/qfieldcloud/core/rest_utils.py
- docker-app/qfieldcloud/core/tests/test_user.py
- docker-app/qfieldcloud/settings.py
- docker-app/qfieldcloud/testing.py
Improve DRF exception handler:
- rethrow unexpected exceptions in tests (so we get the actual trace to the console instead of uninformative error 500)
- don't expose debug details when DEBUG=false
- only log unexpected errors with logger.exception (the other are logged with logger.info, as they are not errors - also we now log the original exception instead of the constructed QFieldCloudException)
(extracted from #254)
> Improve how the API handles exceptions

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/core/views/files_views.py
This way the order in which files are uploaded is not that important anymore.
To save extra unnecessary process jobs, DCIM dir is ignored, since it
consists of staticfiles only.
> When a file is uploaded to a project, start a new process_projectfile job

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/rest_utils.py
- docker-app/qfieldcloud/core/tests/test_delta.py
- docker-app/qfieldcloud/core/tests/test_qgis_file.py
- docker-app/qfieldcloud/core/urls.py
- docker-app/qfieldcloud/core/utils2/__init__.py
- docker-app/qfieldcloud/core/utils2/jobs.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/settings.py
- docker-app/qfieldcloud/testing.py
All files from s3 are now served either using the nginx X-Acccel redirect,
or directly served by django in DEBUG mode.
This way we got rid of the so problematic redirect that was breaking pretty
much every client.
Also, the `files/meta/<projectid>` endpoint looks a bit redundant, but
it all started with the `files/<projectid>` API being so unflexible. Too
late to change now.
> Download file improvements, hiding the s3 urls; No more redirecting fallback

- README.md
- docker-compose.override.dev.yml
- docker-compose.override.local.yml
Note the recommended local development docker-compose is the one with `local` suffix.
Add debugger to the worker wrapper too. It uses different port because:
- conflict with port exposure
- theoretically support parallel debuging, even though it would be clumsy with to VS code editors.
> Debug improvements

- docker-app/qfieldcloud/core/tests/test_packages.py
- docker-app/qfieldcloud/core/tests/test_qfield_file.py
restored some parts of tearDown logic whose removal is probably linked to test failures such as https://github.com/opengisch/qfieldcloud/runs/5225583774?check_suite_focus=true
> remove useless tearDown methods followup

- docker-qgis/Dockerfile
- docker-qgis/entrypoint.py
- docker-qgis/utils.py
While neither `/run/user/0` nor `/var/run/user/0` really exist, this prevents certain types of failure, such as:
- core dumped, as it happens when it is set to a custom dir within the
tmpdir with 700 perms
- error from the dev server:
`WARNING:QGIS_STDERR:QStandardPaths: wrong ownership on runtime directory /tmp/runtime-root, -2 instead of 0`
which causes the internet providers to fail miserably
> Print QGIS version withing the worker and set XDG_RUNTIME_DIR 

- docker-app/qfieldcloud/core/management/commands/createuseraccounts.py
Why they are missing I am not sure, but it happened twice.
> Add a utility CLI that creates missing useraccounts if a user/org is missing one

- docker-app/qfieldcloud/core/models.py
This fix directly affects the permissions check for role reporter, which were failing before, as `delta.method == Delta.Method.Create` was returning false.
> Fix the Delta.Method enums to inherit str, so the string comparison works

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_delta.py
- docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta_project2.json
- docker-app/qfieldcloud/core/utils2/jobs.py
- docker-app/worker_wrapper/wrapper.py
This PR aims to simplify the execution of delta apply jobs within the worker, by always using a predefined list of deltas. This list is created on the time of creation of new delta apply job.
The code should follow the coditions explained here https://docs.qfield.org/reference/qfieldcloud/jobs/#delta-apply-delta_apply-job 
The highlight of this PR is that the M:N `ApplyJobDelta` is populated only within the Django app and the worker-wrapper is just reading from that list.
> Prepare the list of deltas to be applied on the time of creating the job

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_organization.py
Note: this does NOT contain actual monthly bills (which we need to store in the DB, as the number of active of a past month can change if a user is removed from an organization)
> QF-1552: implement function to get number of active users

- README.md
Related to 866c5032d1f2bfebec369db939c1f371d58f2217 the django port changed to 8111 from 8000. This needs to be changed in the README.md
> Update Port where django is running

- docker-app/qfieldcloud/core/utils.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/core/views/package_views.py
- docker-compose.override.test.yml
- docker-qgis/entrypoint.py
- docker-qgis/utils.py
Attachments are unimportant files such as photos, video, documents etc
that do not affect the work of the geospatial project.
- Add `is_attachment` flag to the files/package response to indicate
whether the file is considered an attachment.
- Do not download files within the worker that are flagged as `is_attachment`
- List files from the package and add the files from the original project
files in the attachment directories.
- When a file is requested from the package files endpoint and has an
attachment prefix, first check if the file is available in the package
and if not, try to download it from the original project files.
> Skip downloading attachments in workers

- docker-app/qfieldcloud/core/tests/test_delta.py
- docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta_null.json
- docker-app/qfieldcloud/core/utils.py
- docker-app/qfieldcloud/core/views/deltas_views.py
```
unsupported Unicode escape sequence
LINE 1: ...id, '2c6f40b1-7d2a-4225-be8d-8190d7a691f9'::uuid, '{"clientI...
^
DETAIL:  \u0000 cannot be converted to text.
```
no more
> Replace null bytes in delta json in the delta to prevent pg error

- README.md
- docker-app/qfieldcloud/core/exceptions.py
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_project.py
- docker-app/qfieldcloud/core/views/projects_views.py
- docker-compose.override.test.yml
- docker-compose.yml
Note to myself:
Django does separate select for each of the N relationships, which makes everything incredibly slow.
> Remove `prefetch_related` for 1:n that caused memory leak and super slow responses

- docker-app/qfieldcloud/core/tests/utils.py
Otherwise the default plans will be available for the first test and
deleted for the rest of the tests, which brings a bunch of undefined
errors.
> Delete all existing subscription plans before adding the new

- docker-app/qfieldcloud/core/management/commands/listfiles.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/core/views/projects_views.py
If you use:
```
bucket.objects.filter(...).delete()
```
it deletes only adds a new version with empty size and etag and makes it latest. This means we collect all the file history.
But:
```
bucket.object_versions.filter(...).delete()
```
deletes the file and all it's versions like it never existed.
> Deleting stored package should delete the files and all it's versions

- docker-app/qfieldcloud/core/tests/test_packages.py
- docker-app/qfieldcloud/core/views/package_views.py
E.g. collaborator reader cannot package a project, since the last step of the package job: uploading the files, fails.
> Fix checking for permission when package is uploaded by a collaborator with lower perms

- docker-app/qfieldcloud/authentication/auth_backends.py
- docker-app/qfieldcloud/authentication/tests/test_authentication.py
- docker-app/qfieldcloud/settings.py
Fix https://github.com/opengisch/QField/issues/3195
Quite interesting we didn't find it until now. A follow up would be to prevent resetting a password of an organization.
> Prevent login with organizations or teams

- docker-app/qfieldcloud/core/utils.py
Reading the whole file is not too much of a concern, as the delta files
should not grow indefinitely.
If we decode to utf8, we might get a chunk splitting the utf8 char in two,
therefore creating invalid utf8 character.
Tried to work with bytes directly, but failed. In theory we can safely
remove the null bytes without worrying too much, as null bytes appear
only for null characters in utf8.
Or at least according to this: https://stackoverflow.com/a/6907327/1226137
> Fix replacing null bytes with utf8 conversion but reading the whole file

- docker-app/qfieldcloud/core/exceptions.py
- docker-app/qfieldcloud/core/rest_utils.py
- docker-app/qfieldcloud/core/tests/test_project.py
Fixes for errors logged to sentry. To better review, look at the individual commits (referring to the sentry issue), since the last one refactors the error handler.
I'm not 100% sure doing this all in the exception handler is the right place, because stuff like `ObjectDoesNotExist` may be an user error (e.g. user entering a wrong URL) but also due to bugs in the code... IMO it would be cleaner to only take care about how exceptions are returned to the user in the handler, but otherwise catch/manage them in the code where we expect them to happen.
> Qf 2134 fix sentry logging

- .env.example
- conf/nginx/templates/default.conf.template
- docker-app/requirements_test.txt
(not ready for review yet)
Groundwork for selenium testing:
- allow `nginx` as a hostname (so the selenium browser can access the app using the proxy instead of django, hence testing the full stack)
- include python-selenium dependency
TODO before merge
> Infrastructure for selenium tests

- docker-app/requirements_worker_wrapper.txt
- docker-app/worker_wrapper/wrapper.py
If `container.logs()` call fails, the container remains dangling since it is never deleted with the python API.
Adding a automatic retry should solve this.
Prevents errors like:
```
Traceback (most recent call last):
File \"/usr/local/lib/python3.8/site-packages/urllib3/response.py\", line 438, in _error_catcher
yield
File \"/usr/local/lib/python3.8/site-packages/urllib3/response.py\", line 764, in read_chunked
self._update_chunk_length()
File \"/usr/local/lib/python3.8/site-packages/urllib3/response.py\", line 694, in _update_chunk_length
line = self._fp.fp.readline()
File \"/usr/local/lib/python3.8/socket.py\", line 669, in readinto
return self._sock.recv_into(b)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call …
```
> Fix dangling QGIS containers eating host's disk space

- docker-compose.yml
Tried to set it up with:
```
ENVIRONMENT = os.environ.get("ENVIRONMENT")
sentry_sdk.init(environment=ENVIRONMENT)
```
but then:
```
sentry_sdk.client_get_options()
```
didn't return the correct environment. Dunno why, but this seems to work.
> Setup sentry environment

- docker-app/requirements.txt
Prevent potential denial of service attack:
https://docs.djangoproject.com/en/3.2/releases/3.2.17/#cve-2023-23969-potential-denial-of-service-via-accept-language-headers
> Bump django to 3.2.17

- docker-app/qfieldcloud/core/tests/test_admin.py
- docker-app/requirements.txt
DB migrations:
- https://github.com/jazzband/django-axes/blob/master/axes/migrations/0008_accessfailurelog.py - Added a new model, no python execution, no scary DB locks expected.
Changelog:
https://github.com/jazzband/django-axes/releases/tag/5.40.1
Changes:
https://github.com/jazzband/django-axes/compare/5.28.0...5.40.1
> Bump `django-axes` dependency to the latest 5.40.1

- docker-app/qfieldcloud/settings.py
Sentry does not validate it's initialization function, but when there is an error, instead of proper error page in DEBUG mode, it just shows "A server error occurred.  Please contact the administrator.".
The problem was introduced with #491
> Fix configuration of Sentry by converting the envvar SENTRY_SAMPLE_RATE to a float

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_admin.py
- docker-app/qfieldcloud/settings.py
- docker-app/requirements.txt
DB migrations:
- https://github.com/jazzband/django-auditlog/blob/master/auditlog/migrations/0008_action_index.py - adds an index, will lock temporarily
- https://github.com/jazzband/django-auditlog/blob/master/auditlog/migrations/0009_alter_logentry_additional_data.py - adds a nullable JSON field, should be fast
- https://github.com/jazzband/django-auditlog/blob/master/auditlog/migrations/0010_alter_logentry_timestamp.py - adds a non-nullable timestamp field with default value, will be slow but not terrible
- https://github.com/jazzband/django-auditlog/blob/master/auditlog/migrations/0011_logentry_serialized_data.py - adds a nullable JSON field, should be fast
- https://github.com/jazzband/django-auditlog/blob/master/auditlog/migrations/0012_add_logentry_action_access.py - no DB changes, …
> Bump django-audit dependency to the latest 2.2.2

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/models.py
By default django is rendering all possible values in a select field, which
is no longer scalable with 60k users. Therefore an autocomplete field is
rendered.
Also make UserAccount representation nicer from "Useraccount 1" to "suricactus (UserAccount)".
> Speed up QFieldCloud admin by referencing user with autocomplete view

- docker-app/qfieldcloud/subscription/models.py
For historical reasons, the name is `active` and should be changed to `active` soon after release.
> Added docs to clearly state the misleading name of `SubscriptionQuerySet.active()`

- .github/workflows/test.yml
- scripts/check_envvars.sh
@why-not-try-calmer seems the split of the CI in two broke the `pipenv` dependency in the latter part. No idea why I overlooked that https://github.com/opengisch/qfieldcloud/pull/520 is failing...
> Remove the pipenv dependency for envvar validation

- docker-app/qfieldcloud/core/utils2/storage.py
The function assumes the versions are sorted from latest/newest to oldest versions. However, this was no longer the case and was asserting.
> Fix deleting versions with `include_older=True`

- docker-app/qfieldcloud/core/adapters.py
NOTE `allauth` depends on the `PRESERVE_USERNAME_CASING` to make `iexact` lookups. When set to `False` as it is now, all `Person` usernames are stored as lowercase. However, usernames for `Organization` or `Team` are not stored lowercase and then `allauth` does not check for them.
TODO check what are the consequences if we don't add all of these and change the `PRESERVE_USERNAME_CASING` to `True`.
> Users getting error 500 when trying to register with username taken by an Organization

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/subscription/models.py
- docker-app/qfieldcloud/subscription/tests/test_package.py
- docker-app/requirements.txt
- Make `date_joined` and `last_login` in `People` readonly
- Add `django-nonrelated-inlines` dependency
- Make add and delete permissions for inline UserAccount simpler
- Add better representation for subscriptions
- Show `date_joined` in `OrganizationAdmin`
- Shorten the owner column name in `OrganizationAdmin`
> Add some admin improvements

- docker-app/qfieldcloud/core/views/files_views.py
Trying to debug why it seems the clients never sent the file object.
> Added logs when `file` is not found in `request.data`

- docker-app/qfieldcloud/core/utils.py
As suggested here https://github.com/boto/boto3/issues/801#issuecomment-875140699,
The occasional error we get `KeyError: 'endpoint_resolver'` should be fixed if we replace `boto3.client()` with `s3_session.client()` .
> Always use boto3 session when creating different objects.

- docker-app/qfieldcloud/subscription/models.py
The timestamps of the two overlapping subscriptions looks suspiciously close to each other.
> Log timeframes

- .pre-commit-config.yaml
While useful in a subset of situations, it brings additional cognitive pressure to evaluate if it is used properly.
It's behavior is not intuitive for people coming from other languages and may lead to critical bugs we can just avoid.
The good old if/else served the python users for 30 years, I believe we can keep until we see real limitations.
> Forbid usage of match/case in the codebase

- docker-app/qfieldcloud/settings.py
In theory, we should mark all docker-compose envvars mandatory. But it's not the right moment for that right now, already in the backlog.
Fixes a bug introduced by #587 .
> Fix backwards compatibility when `QFIELDCLOUD_DEFAULT_TIME_ZONE` is not set

- docker-app/qfieldcloud/core/admin.py
> Added column showing number of recently active users to projets under `OrganizationAdmin`

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/settings.py
Bigger lists makes the whole app slower and does not bring a lot of benefits with 100s of thousands of users.
> Reduce the default Django list per page from 100 to 20 items

- docker-app/qfieldcloud/core/admin.py
#QF-2611
Django adds -pk ordering even when custom order field is defined.
I did some `EXPLAIN ANALYZE` on test.qfield.cloud db without serious analysis seems to speed up query a bit ...
> No extra order -pk in admin change list

- docker-app/qfieldcloud/core/views/package_views.py
Actually they may have changed in the meantime, but HTTP clients, including Qt.
> Fix misleading the HTTP clients to cache package files for 10 minutes

- docker-app/qfieldcloud/core/exceptions.py
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_job.py
- docker-app/qfieldcloud/core/tests/test_project.py
- docker-app/qfieldcloud/settings.py
- docker-app/qfieldcloud/subscription/exceptions.py
Summary:
Synchronization is not possible if user account unsufficient (inactive, over qouta, no online layers) -> PackageJob NOT created. Pushes are always possible -> ApplyJob created. Poject creation is rejected from WebUI and QFsync -> ProcessprojectfileJob NOT created, Project NOT created.
Further ...
New behaviour:
**useraccount inactive**
Qfieldsync: on create new project when  => `Permission denied .. useraccount is inactive`
-> no Job or Project is created at all.
Qfield: 
- push: always works
- synchronize: ` ... Permission denied because useraccount inactive ... `
**online vector layers on account that doesn't support**
Qfield:
- push: always works
- synchronize: `... user accounts'plan is insufficient ... `
**useraccount over quota**
Qfield:
- push: always works
- synchronize: …
> Reject job and project creation for unsufficient useraccount

- docker-app/qfieldcloud/core/models.py
Calling `QgsVectorLayer().type().name` QGIS 3.30.x returns "Vector", while previous versions return "VectorLayer"
Related issue: https://github.com/qgis/QGIS/issues/53023
Fixes regression introduced in #637 .
> Workaround vector layer type rename in QGIS 3.30

- docker-app/qfieldcloud/subscription/tests/test_subscription.py
As seen here: https://github.com/opengisch/qfieldcloud/actions/runs/4931191111/jobs/8812978269#step:10:333
> Fix flaky subscription test due to microseconds overlaps

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/permissions_utils.py
- docker-app/qfieldcloud/core/tests/test_file_upload_policy.py
- docker-app/qfieldcloud/core/tests/test_job.py
- docker-app/qfieldcloud/core/tests/test_packages.py
- docker-app/qfieldcloud/core/tests/test_qfield_file.py
- docker-app/qfieldcloud/core/tests/utils.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/core/views/qfield_files_views.py
This PR adds:
- in `files_views.py` that we do not throw QoutaError if client_type is `worker` or `qfield`
- in `qfield_files_views.py` throw early before packaging for qfield
- in `models.py` that we never throw on ProcessProjectFileJob
The rest is testing related because https://github.com/opengisch/qfieldcloud/pull/655 still needs some fixes
> Always accept file uploads from Qfield

- docker-app/qfieldcloud/core/management/commands/dequeue.py
- docker-app/worker_wrapper/wrapper.py
Pretty much the title. Django ORM otherwise saves all properties.
> Be more strict when updating jobs, set `update_fields` on each `.save()`

- docker-app/qfieldcloud/notifs/tests/test_notifs.py
- docker-app/requirements.txt
Let another round of bumped dependencies. At first look it seems to work, let's wait a week before releasing it.
> Bump various deps

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_deleteorphanedfiles.py
- docker-app/qfieldcloud/core/tests/test_delta.py
- docker-app/qfieldcloud/core/tests/test_job.py
- docker-app/qfieldcloud/core/tests/test_organization.py
- docker-app/qfieldcloud/core/tests/test_permission.py
- docker-app/qfieldcloud/core/tests/test_project.py
- docker-app/qfieldcloud/core/tests/test_user.py
- docker-app/qfieldcloud/core/tests/utils.py
- docker-app/qfieldcloud/notifs/tests/test_notifs.py
- docker-app/qfieldcloud/subscription/models.py
Note there is a slight change in behaviour of `Subscription.is_active`, which now takes into account `the active_since`/`active_until`.
> Added managed_by and activeness in Subscription QuerySet

- docker-app/qfieldcloud/core/exceptions.py
- docker-app/qfieldcloud/core/middleware/requests.py
- docker-app/qfieldcloud/core/tests/test_qgis_file.py
- docker-app/qfieldcloud/core/utils2/sentry.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/settings.py
This PR uploads to Sentry a string representation of some fields on `request.data` which _might_ be meddled with by serializers/middlewares (one pre- and one post-serialization representation, which together can be used to identify suspicious differences). 
The reasoning is: if we have differences and also miss files, then the cause of the missing files might manifest in the differences.
This PR also sends a 50-line long traceback allowing to follow calls to Django Middleware functions. This is useful in cases Sentry's built-in traceback falls short.
The hope is that these artifacts will help pinpoint the cause of the missing files error.
In addition to this debugging goal the PR adds logic for dealing with uploads featuring too many files and the corresponding unit test.
__Part 1 …
> Debug `EmptyContentError: Empty content`

- .github/workflows/test.yml
- docker-app/qfieldcloud/core/migrations/0009_geodb.py
- docker-app/qfieldcloud/core/models.py
What looked like adding a single line of code turned into me arm-wrestling the Django migration writer. 
The issue is basically that the migration writer doesn't know how to serialize bound functions -- functions parameterized with an implicit reference -- and that static methods seem to be considered as bound functions.
I went for the "brutal" way of solving this: i.e. extracting the static method to a top-level function. There are other ways. Please make a commit suggestion if you are not happy with the way I went for.
> QF-2700 Run makemigrations --check right after building

- docker-app/qfieldcloud/core/tests/test_qgis_file.py
- docker-app/qfieldcloud/core/views/files_views.py
_Source_:
https://app.clickup.com/t/2192114/QF-2711.
_Problem_:
The `download_project` step used in the `process_projectfile` workflow makes a call to `qfieldcloud_sdk` to the effect that the sdk will try and GET project files under a given project id. However, the attempt sometimes fails on "500: Internal Error", with the caller being offered little to no information about the error. 
_Proposal_:
This PR proposes to offer callers more information about such failures. It delineates all the I/O actions that might raise, collect the possible exceptions, and returns the first one raised as part of the response.
> QF-2711 Adding a few failsafes around ListFilesView.get()

- docker-qgis/apply_deltas.py
We are running without transaction for quite some time without troubles.
> Kill the `--transaction` parameter as not needed and very outdated 

- docker-app/qfieldcloud/core/admin.py
This way we can now configure certain staff users to have access to  certain Django admin models only. What is more, we can make this access read-only. I will do this manually in the admin after releasing this  branch.
@m-kuhn @faebebin ideally I would like to have this in the upcoming release.
> Enable Groups model and groups field in People view in Django admin

- .github/workflows/test.yml
__TL;DR__
I am not able to make #674 work. I submit this as an ersatz. This PR borrows from design of the PR it supersedes, having each job in the matrix handle a separate batch of tests, grouped by Django app.
As for #674 it shaves off some precious minutes, and even more so if we are able to fix flakiness once and for all, because then we can run the tests on either `pull_request` or `push`.
__Comparison with #674__ 
- it runs to completion
- it is less efficient: while in #674 the Docker images where first built in parallel _once_ and then downloaded and used in each job in the matrix, now the images need to be built _for each job in the matrix_.
- it means much less maintainance
- it provides much faster feedback for PRs authors, especially for PRs not touching `core`
> QF-2657 Improving tests on CI: parallel build/testing

- .gitattributes
When the repository is cloned on Windows, all newline characters are converted to CLRF format. This causes a problem when running images that contain bash scripts. Linux scripts are not compatible with this newline character format and cause an error:
`standard_init_linux.go:228: exec user process caused: no such file or directory`
> New line handling

- docker-app/qfieldcloud/core/tests/test_sentry.py
- docker-app/qfieldcloud/core/utils2/sentry.py
> QF-2704 Making sure strings are encoded when sending to Sentry

- docker-app/qfieldcloud/core/tests/test_organization.py
I am pretty sure this is meant?
> Fix wrong test in test_organization

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/subscription/models.py
Shows the active members, that have created a Job or a Delta for the Organization during the running stripe billing period in the admin.
The list of users in the detail view
(if no active members)
Dropped the active members count in the list_view - it would slow down too much:
It adds 4 Queries per organization. Without it is 6 Queries in total.
now:
before:
> Show active members in the Organization Admin

- docker-app/qfieldcloud/core/admin.py
Email export was not working due to order of URL patters to check.
Added columns `verified`, `last_login`, `owner_last_login`.
Check bottom right where the button is:
> Fix email export and add extra columns to the export

- docker-app/worker_wrapper/wrapper.py
Whenever the docker engine kills a container there is exit code 137. However, sometimes the "murder" happens when the job is still in the DB. In such cases, the job is stuck in "Started" status forever. This PR is setting the job into "failed" status.
> Set final status to jobs that have been killed by docker engine

- docker-app/qfieldcloud/settings.py
Will ignore the number one "error" there is --> wrong login credentials provided.
I was wondering if we should only ignore exceptions that are unhandled (e.g. this one is handled, so it will still be hidden). @faebebin any idea?
> Ignore validation errors for sentry

- docker-qgis/requirements.txt
Should make the workers considerably faster as the number of project files increase.
> Bump `qfieldcloud-sdk` from `0.6.1` to `0.7.0` to ignore the `sha256` metadata

- docker-app/qfieldcloud/core/pagination.py
- docker-app/qfieldcloud/core/tests/test_api.py
- changed behaviour of QfcLimitOffset pagination class to not limit results unless a limit offset param is found in the request
- adjusted tests
> QfcLimitOffsetPagination default limit

- docker-app/qfieldcloud/core/serializers.py
Otherwise updating the project using the API will automatically change the project owner to the currently authenticated user.
> Do not steal the ownership of the project if not explicitly provided

- docker-app/qfieldcloud/core/querysets_utils.py
Needed by https://github.com/opengisch/qfieldcloud-private/pull/460.
> Inconsistent organization member lists, return `Person` instead of `OrganizationMember`

- docker-app/qfieldcloud/core/exceptions.py
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/permissions_utils.py
- docker-app/qfieldcloud/notifs/cron.py
- docker-app/qfieldcloud/subscription/models.py
- docker-app/qfieldcloud/subscription/tests/test_package.py
Remove @deprecated objects that are referenced only in tests or nowhere.
Should remove some noise / unused code.
> Cleanup @deprecated code that affect only tests

- docker-app/qfieldcloud/core/middleware/requests.py
- docker-app/qfieldcloud/core/tests/test_sentry.py
- docker-app/qfieldcloud/core/utils2/sentry.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/settings.py
A few clarifications and observations:
- Actually this is fine => ~~`DownloadPushDeleteFileView.post()` does not trigger the `parse()` method of its declared parser_class (MultiPartParser), because I did subclass this parser class in a previous version of this PR, and my override of `parse()` never triggered in my tests~~
- This is done => ~~room for improvement: ensure that the intended `parse()` function is called, so that we can debug more from that context; this might open the door to reading the request.body only for requests that fail, and not all of them as is the case here.~~
> Sending raw body to sentry

- docker-app/qfieldcloud/core/utils.py
- docker-app/qfieldcloud/core/views/files_views.py
As of current `master` the `e_tag` property of `S3ObjectVersion` will evaluate to `None` in certain edge cases, causing Exceptions (see for example https://github.com/opengisch/qfieldcloud-private/pull/474). This PR ensures `S3ObjectVersion.e_tag` never lies about its type.
> Slight readability improvement on etag preparation for files

- docker-app/worker_wrapper/wrapper.py
- docker-qgis/entrypoint.py
While working on a recent task I cleaned up some type hints.
> Type hints in worker_wrapper

- .github/workflows/test.yml
- .mypy.ini
- .pre-commit-config.yaml
- docker-app/qfieldcloud/authentication/authentication.py
- docker-app/qfieldcloud/authentication/tests/test_authentication.py
- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/invitations_utils.py
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/permissions_utils.py
- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/tests/test_delta.py
- docker-app/qfieldcloud/core/tests/test_qfield_file.py
- docker-app/qfieldcloud/core/tests/test_sentry.py
- docker-app/qfieldcloud/core/tests/utils.py
- docker-app/qfieldcloud/core/utils2/projects.py
- docker-app/qfieldcloud/notifs/signals.py
- docker-app/qfieldcloud/subscription/models.py
This extends the scope of the static type-checker to also encompass docker-app and docker-redis.
> Mypy app-wide scope

- docker-app/qfieldcloud/authentication/auth_backends.py
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/permission_check.py
- docker-app/qfieldcloud/core/permissions_utils.py
- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/tests/test_packages.py
- docker-app/qfieldcloud/core/utils.py
- docker-app/qfieldcloud/core/utils2/audit.py
- docker-app/qfieldcloud/core/utils2/jobs.py
- docker-app/qfieldcloud/core/utils2/projects.py
- docker-app/qfieldcloud/subscription/models.py
- Fixes an issue introduced by https://github.com/opengisch/qfieldcloud/pull/786/files.
- Fixes misleading docs in Authentication backend.
- Remove all `List, Dict, Tuple, Optional, Union` from docker-app
> Fix incorrect assert for `active_since` when creating a `Subscription`

- docker-app/qfieldcloud/subscription/models.py
- docker-app/qfieldcloud/subscription/tests/test_subscription.py
It does not track changing organization ownership yet. IMO not necessary?
> Track remaining_trial_organizations on org owner

- docker-app/worker_wrapper/wrapper.py
Please consider the associated ClickUp task for details.
> Catching exceptions earlier when trying to cancel orphans containers with empty references

- docker-app/qfieldcloud/urls.py
Since the schema endpoint has been changed, we broke the integration on https://docs.qfield.org/reference/qfieldcloud/api/ . I overlooked the endpoint renaming.
@why-not-try-calmer was there any reason you rename endpoints?
> Fix OpenAPI and Swagger URLs and CORS

- .github/workflows/test.yml
- docker-app/qfieldcloud/authentication/authentication.py
- docker-app/qfieldcloud/core/exceptions.py
@nirvn @mbernasocchi as discussed
token related stuff is like this:
```
{
"code": "token_authentication_failed",
"message": "Token authentication failed"
}
```
vs login failed:
```
{
"code": "authentication_failed",
"message": "Authentication failed"
}
```
> Add a differentiation between login+pwd vs token errors in the API

- docker-app/worker_wrapper/wrapper.py
Otherwise get out of /tmp storage with long uptime.
> Remove the tmpdir with feedback and thumbnail after job is finished

- docker-app/qfieldcloud/core/admin.py
Team admin can be saved without the need to manually edit the username
|-|-|
| ![image](https://github.com/opengisch/qfieldcloud/assets/2820439/7059a110-5476-4a3b-8fae-628d44bf0744) | ![image](https://github.com/opengisch/qfieldcloud/assets/2820439/04fa0e38-3092-4385-88e8-56ed236928c0) |
> Hide the organization prefix (`@<org>/) in the team admin

- docker-app/qfieldcloud/core/models.py
|-|-|
| ![image](https://github.com/opengisch/qfieldcloud/assets/2820439/23b76d7c-2f68-4155-8a35-b09592496c8e) | ![image](https://github.com/opengisch/qfieldcloud/assets/2820439/52af0dc1-efa3-44f7-8c73-eb904cdec4de) |
> When a layer is invalid due to localized datasource, show link to docs

- .env.example
- README.md
- docker-compose.override.dev.yml
- docker-compose.override.local.yml
The `GEODB_PORT` is used as part of the connection string within the compose stack. The `HOST_GEODB_PORT` is used to expose the PG port to the host. The code was trying to connect to the host port from within the compose stack.
> Fix the usage of `GEODB_PORT`, it should be `HOST_GEODB_PORT`

- docker-app/qfieldcloud/core/admin.py
"owner__type" for the filter would suffice functionality wise.
But the filter title would then be "By type" in the UI, which is semantically unclear, hence the SimpleListFilter subclass.
> QF-3714 In Projects admin page, add a owner type filter - by user or by organization

- docker-qgis/requirements_libqfieldsync.txt
This was wrongly applied on non-spatial layers, which caused them to be exported as empty layers.
Fix #874
> Fix geometry-less exported as empty layers

- docker-app/qfieldcloud/subscription/admin.py
Because in Sentry we list the "id" it helps to find the Subscription of concern
> Add "id" to `SubscriptionAdmin.search_fields`"

- docker-app/wait_for_services.py
Currently, if postgres never responds, `wait_for_services.py`  just hangs indefinitely, never returning.
> QF-3825 wait_for_services.py handles if pg never responds in the timeout window

- docker-app/qfieldcloud/subscription/admin.py
I understood the expiration date field to be the `active_until` field, correct me if I am mistaken (other related fields: `current_period_until`, `requested_cancel_at`).
> QF-3832 Add filter that shows all subscription that expire within 1, 2, or 4 weeks

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/templates/admin/job_change_form.html
The re-run button sets the job back to "pending" status.
However, on my local setup, jobs are systematically failing as the projects are missing their files.
Requires maybe some more tests?
> QF-3716 Add possibility to rerun job in the Admin

- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/core/views/package_views.py
Serve only `md5` checksum instead of `sha256` checksum to gain extra performance when downloading packaged files in QField. The `sha256` causes N+1 requests to the S3 storage, therefore makes the QFieldCloud response on the `packages/<project-id>/latest` endpoint super slow.
See https://github.com/opengisch/QField/pull/5040
> Support `skip_metadata` `on packages/<project-id>/latest` request to boost performance

- docker-app/qfieldcloud/core/management/commands/status.py
- docker-app/qfieldcloud/core/utils.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/core/views/files_views.py
- docker-app/qfieldcloud/core/views/package_views.py
- docker-app/qfieldcloud/core/views/status_views.py
Removed `utils.get_s3_object_url()` which was the main culprit for errors on AWS tests.
> QF-3818 Make connexion to s3 more resilient

- docker-app/qfieldcloud/core/utils2/storage.py
Works fine for thumbnail, but I get `403 forbidden` for avatar at https://localhost/api/v1/files/public/users/<USER>/avatar.svg
Seems independant of `ACL` policy...
> QF-3851 Remove S3 ACL parameter for avatar/projects thumbnails

- docker-qgis/entrypoint.py
- docker-qgis/qfc_worker/process_projectfile.py
- docker-qgis/qfc_worker/utils.py
- docker-qgis/requirements_libqfieldsync.txt
This PR reworks the packaging job workflow to prevent _3_ project loads and instead rely on a single initial load. This can lead to massive speed gains on complex projects and/or projects containing remote sources that are slow.
Requires the following libqfieldsync improvements: https://github.com/opengisch/libqfieldsync/pull/68
> Speed up packaging

- docker-app/qfieldcloud/core/middleware/timezone.py
We did the wrong check to get the user timezone and we never entered this if body. Note we already assume that the user has a `useraccount` which is safe assumption.
> Fix typo to fix timezones for users from the other side of the world

- docker-app/qfieldcloud/core/middleware/timezone.py
This reverts commit 8510d2369a5b53fda10c99f7cd683c861a6b0638. 
Reverts #912 . 
Prevents creating subscriptions active in the future. Proper fix will be issued in calmer times, sorry fellow friends from other parts of the world.
> Fix missing active subscription creation by reverting the timezone fixes in #912

- docker-qgis/entrypoint.py
The removed if condition somehow slipped in, I don't see why it was added in the first place. I guess it was part poor attempt to rewrite the original code from commit `1df4f4090d847e50422881aca1af2595eb2ddb09`:
```
mapsettings.setLayers(
[layers[key] for key in layers if type(layers[key]) == QgsVectorLayer]
)
extent = mapsettings.fullExtent()
```
However, it is not clear why the if condition has been inverted, neither why the if condition was needed in the first place. If one says it's to prevent the infinite extent of the XYZ layers, the current code already checks for that a few lines below:
```
if layer_extent.isNull() or not layer_extent.isFinite():
continue
```
In any case, this line is removed for good now.
> Do not exclude vector layers when estimating the extent of the project

- .env.example
- scripts/check_envvars.sh
- scripts/init_letsencrypt.sh
Problem for nginx cert update was `init_letsencrypt.sh` uses `CONFIG_PATH=./conf`, but qfieldcloud-nginx config has been moved to the `docker-nginx` folder.
Hence changing `CONFIG_PATH=./` by default and completing the subsequent paths in `init_letsencrypt.sh`
> Fix init_letsencrypt.sh CONFIG_PATH

- docker-qgis/qfc_worker/utils.py
@suricactus , am I missing something completely obvious here or are we missing a setBadLayerHandler call since v0.26.0?
> Fix localized path regression

- docker-qgis/Dockerfile
- docker-qgis/requirements.txt
This will automagically bump `gdal` from 3.4.1 to 3.8.4. We actually care that the GPKG patch from 3.4.2 is present. See the QGIS patch here: https://github.com/qgis/QGIS/pull/47098/
> Bump to latest Ubuntu 24.04 and QGIS 3.36.2

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/templates/admin/edit_inline/tabular_customized.html
- docker-app/qfieldcloud/core/templates/admin/edit_inline/tabular_extended.html
|-|-|
| ![image](https://github.com/opengisch/qfieldcloud/assets/2820439/c9412988-0d80-4604-a010-653070cda231) | ![image](https://github.com/opengisch/qfieldcloud/assets/2820439/23a34435-00b6-4b06-81ec-66193af5e31c) |
Clicking on the link also preloads the current project id.
@boardend it's super hacky way to do it without directly touching the template. No strong opinion if we have to merge it as it is, +0.5 on my side.
> Hack a way to add extra HTML in `InlineTabular` admin templates

- docker-app/qfieldcloud/core/cron.py
- docker-app/worker_wrapper/wrapper.py
Fixed delta apply stuck in started, there were two cases in `cron.py` and `wrapper.py`. See clickup for detailed discussion of the error investigation.
In addition, I ensured error logs were more thoroughly downstreamed from jobs to deltas in `DeltaApplyJobRun.after_docker_exception()`.
Do review thoroughly how I handled models update (especially in `cron.py`) as I am not super-familiar with Django models ;-)
> QF-4070 fix Delta Apply stuck in "Started"

- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/requirements.txt
- docker-app/requirements_worker_wrapper.txt
The CI tests returned error messages like:
> Exception: Processing did no finish, did the worker hang ?
This was cause because the `worker_wrapper` gets on start:
> docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker
NOTE since we are using multi-stage builds in docker, the `requests`
dependency was forced on the previous layer than the `worker_wrapper`
itself.
> Fix the failing worker_wrapper and tests by requests==2.32.0

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/templates/admin/project_change_form.html
- This adds a link to the project admin form in order to navigate to the list of jobs filtered by the project id
> Create a link to the project jobs in the project admin view

- docker-app/worker_wrapper/wrapper.py
#941 follow up:
- Execute "after_docker_exception" on DOCKER_ENGINE_SIGKILL (this ensures status of related deltas gets updated)
> Execute "after_docker_exception" on DOCKER_ENGINE_SIGKILL

- docker-app/qfieldcloud/subscription/migrations/0004_auto_20220923_1602.py
- docker-app/qfieldcloud/subscription/models.py
When hosting a new QFieldCloud instance, a default subscription plan is created. This change ensures that the status of this plan is `ACTIVE_PAID`, so that created users can create/use projects on that instance as expected.
This change won't affect existing QFieldCloud instances in any way.
> Set initial created subscription plan status to ACTIVE_PAID

- docker-qgis/Dockerfile
The change I guess is obsolete by now.
> We already have quite fresh `pip`, no need to force upgrade

- .env.example
We don't want a real address to be used in production
> Replace email address with demo address

- docker-qgis/Dockerfile
Issue #975 Patch: Unknow instruction Types in Dockerfiles
The block COPY with EOF syntax return error under Synology container Builder
> Patch Dockerfile: EOF not valid under all build OS

- docker-app/qfieldcloud/core/models.py
When creating a new user in the QFieldCloud admin interface, the user's timezone is always "Europe/Zürich", even if the `QFIELDCLOUD_DEFAULT_TIME_ZONE` / `TIME_ZONE` variables are different
This PR sets the timezone of a new user to the env timezone by default
> Set new user's default timezone to the settings one

- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/views/collaborators_views.py
In addition, prevent attempts to add other `User` subclasses as project
collaborators
> When adding a collaborator via the API, add created_by/updated_by

- docker-app/Dockerfile
I like ipython for block editing and much more. If installed, is used as default by `django manage.py shell_plus` . 
Suggest add it if DEBUG_BUILD is set.
> Enhance shell_plut with ipython if DEBUG_BUILD

- docker-compose.yml
Had to verify that the qgis container gets immediately killed, which is not great.
How to test:
1) add `sleep(10000)` to the start of `docker-qgis/entrypoint.py` 
2) verify it is still running after a few minutes
3) `docker compose stop`
4) check if QGIS is still running:
- before the changes: it is not
- after QGIS: it is waiting for the end
> Make sure the qgis continues to run

- docker-app/qfieldcloud/core/exceptions.py
- docker-app/qfieldcloud/core/rest_utils.py
(we reuse the http code to determine if it's sever error or client error)
> Make the information whether an error should be logged to sentry  part of the error class

- docker-app/qfieldcloud/core/models.py
> Do not check for email uniqueness if the email is not populated

- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
The old module does not support Django 4+
> Retire the outdated `django-migrate-sql-deux` and use `django-migrate-sql-3`

- .github/workflows/build_and_push.yml
Build and push was missing the `push:` entry, so it was not pushing over its build.
> Fixing github Build-and-push so that it actually pushes

- docker-app/qfieldcloud/authentication/admin.py
- add a token filter based on client type (e.g. `QField`, `QFieldSync`, `Browser`...)
- add a custom action to disable a token by setting it's expiration date to now
> Add token filter and action

- docker-app/qfieldcloud/core/drf_utils.py
- docker-app/qfieldcloud/core/views/projects_views.py
Add an ordering filter for the `ProjectViewSet` that allows ordering by :
- `owner`'s username
- `name`
- `created_at`
See[QF-4681](https://app.clickup.com/t/2192114/QF-4681)
> Add projects API ordering

- docker-app/qfieldcloud/settings.py
- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
Django auditlog version 3.0.0 migrates the `changes` from `text` to `jsonb` datatype. Since QFieldCloud has millions of audits, the migration will lock the database for hours. This problem was recognized by the developers and they added two step migration: there are two fields to store the `changes`, the old text based one and the new json based new one. Read more: https://django-auditlog.readthedocs.io/en/latest/upgrade.html
We have to remove the `AUDITLOG_TWO_STEP_MIGRATION` and `AUDITLOG_USE_TEXT_CHANGES_IF_JSON_IS_NOT_PRESENT` settings in the future after `manage.py auditlogmigratejson` has been called. THe `auditlog_logentry.changes_text` shall be removed manually after that.
> Bump `django-auditlog` to 3.0.0+

- docker-app/qfieldcloud/core/admin.py
GeoDB was an experiment that is hard to manage and should not be in the core app. It is still used in the tests, so the functionality must stay.
See https://github.com/opengisch/QFieldCloud/issues/1067
> Kill GeoDB admin

- docker-qgis/Dockerfile
> Bump QGIS to 3.40.1

- .github/workflows/test.yml
The `no-commit-to-branch` prevents from accidental commit to master locally. It is not needed to run on the CI. Whatismore, it has to be disabled, otherwise it causes merge commits to fail.
> Fix pre-commit check on the CI that fails on commits merged to `master`

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/tests/test_team.py
- docker-app/qfieldcloud/core/urls.py
- docker-app/qfieldcloud/core/views/teams_views.py
New endpoints have been created for managing both teams and member under organization for CRUD actions
> Add Teams Endpoints to manage teams

- docker-qgis/qfc_worker/utils.py
This is only visible in the `Job.feedback_json`, but makes much more sense to the user and the developer when debugging.
> [refactor] Add error message for the `FileNotFoundError` instead of just showing the filename

- docker-app/qfieldcloud/core/cron.py
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_packages.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/worker_wrapper/wrapper.py
This simplifies some of the future code that is coming in QF-2760.
> [refactor] Make functions in `utils2.storages` us the `Project` instance, not only the `project_id`

- docker-app/qfieldcloud/core/tests/test_packages.py
Seems when this function was first created, someone forgot to make the filename dynamic.
> [tests] Fix hardcoded file name when the package files are downloaded

- docker-app/qfieldcloud/core/tests/test_team.py
We name everything with the same name to make our life much easier when running tests via the CLI.
> [tests] Rename `TeamsTestCase` to `QfcTestCase` as all the tests on QFieldCloud

- docker-app/qfieldcloud/core/exceptions.py
- docker-app/qfieldcloud/core/tests/test_project.py
There are some exceptions that have HTTP statuses that do not correspond to what is actually happening. The statuses are wrong for historical reasons.
Please check the individual commit messages.
> [BREAKING] [refactor] Update the HTTP error codes for some of the exceptions

- docker-app/qfieldcloud/subscription/tests/test_job_creation.py
The test is checking whether the user is able to create a job based on the current subscription status (activity,storage,etc...). So its belong to subscription rather than core.
> Move `core.test_job` to `subscription.test_job_creation`

- .mypy.ini
- .pre-commit-config.yaml
- docker-app/qfieldcloud/core/drf_utils.py
- docker-app/qfieldcloud/core/exceptions.py
- docker-app/qfieldcloud/core/pagination.py
- docker-app/qfieldcloud/core/views/teams_views.py
This PR introduces the following updates to enhance type checking in our project:
Examples of issues:
1. `from rest_framework.views import View` --> The mypy-drf-plugin is strict about ensuring attributes or classes explicitly exported by a module. In simply words, mypy complains because it’s not officially listed in the __all__ attribute of the rest_framework.views module.
> Add `djangorestframework-stubs` for better typing

- docker-qgis/Dockerfile
I was using `$PYTHONPATH` in a context where I cannot expect it to exist.
> Fix GitHub warning that variables should be defined before their use

- docker-app/qfieldcloud/settings.py
Remove the code needed for the two step migration, as it was already ran on app.qfield.cloud
> [optimization] Migrate `django-auditlog` records to `jsonb` datatype

- docker-app/qfieldcloud/core/models.py
The error was due to reference within a class for a class member without namespacing with the  class itself, or reference with `Status` instead of `Project.Status`.
> Fix an error from `drf-spectacular` that returns 500 on GET /swagger.yml

- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/tests/test_team.py
- docker-app/qfieldcloud/core/urls.py
- docker-app/qfieldcloud/core/views/teams_views.py
Basically we can kill theGET /organizations/<organizaztion>/teams/<team>/member   and GET /organizations/<organizaztion>/teams/<team>/member/<member>    . We add the new key members  to the TeamSerializer .
Follow up of #1031
> Simplify the teams endpoints removing unnecessary GET endpoints

- docker-app/qfieldcloud/core/serializers.py
The problem comes from the fact that `teamname` is a runtime property of the `Team` class and not an actual database  field. In addition we were using `Team.object.values()` which returns an `Iterable[dict]`, instead of `Iterable[Team]`. So even if it returned the right type, it would have been terribly slow, due to N+1 situation.
This problem made the `/user/<username>/organization` return an error, therefore prevented QFieldSync from selecting the available organizations for the team.
> Fix getting the list of available teams per organization

- docker-app/Dockerfile
- docker-app/qfieldcloud/core/middleware/timezone.py
Basically we need to install all of them with `zoneinfo` package on
Ubuntu. It is also present as pip package, but I believe the Debian guys
are better at handling this.
> Fix missing timezones

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_jobs.py
- docker-app/qfieldcloud/core/tests/testdata/simple_bumblebees_wrong_localized.qgs
This PR will :
- 1 (invalid) layer with a datasource with non existing filename
- 1 (invalid) localized layer with a datasource with non existing filename
- 1 (valid) localized layer with a datasource with existing filename (QFC should consider it as invalid because it is localized)
> Add test to prevent regressions if `BadLayerHandler` does not work during `packaging` or `process_projectfile`

- docker-app/qfieldcloud/settings.py
- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
This PR upgrades `django-allauth` dependency version to a newer one :
> Bump django-allauth to 65.3.1

- docker-app/qfieldcloud/settings.py
- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
This PR bumps the dependency to its newest version.
`axes`'s changelog: https://github.com/jazzband/django-axes/blob/master/CHANGES.rst#701-2024-12-02
Notable breaking changes: https://django-axes.readthedocs.io/en/latest/2_installation.html#version-7-breaking-changes-and-upgrading-from-django-axes-version-6
To be tested :
- try 6 unsuccessful logins with a correct username and a fake password -> custom QFC lockout page should appear, displaying username :
- try 6 unsuccessful logins with previous user's email address and a fake password -> custom QFC lockout page should appear, displaying email address:
- delete the access attempts in the admin page (or wait for 30min), then:
- try again a login with username and correct password -> should be logged in
- log out and try again a login …
> Bump `django-axes` to v7.0.1 and `django-allauth` to 65.3.1 

- docker-app/requirements/requirements.in
Removes `django` v4.2.16 dependency that was introduced by accident [in this commit](https://github.com/opengisch/QFieldCloud/commit/93e1935cf73e8ab39bf9510092cfb63d66cce8db).
Was introducing some `pipcompile` errors since targeted `django` version is 4.2.17, at the end of the file.
> Remove useless django 4.2.16 dependency

- .github/workflows/sync_translations.yml
- .pre-commit-config.yaml
This PR is intended to fix the Transifex synchronization CI GitHub workflow for QFieldCloud Django strings.
Check this successful manually triggered Transifex sync Action : https://github.com/opengisch/QFieldCloud/actions/runs/13183139676.
> Add `.env` file CI step before generating Django strings for Transifex

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/models.py
- docker-qgis/entrypoint.py
- docker-qgis/qfc_worker/utils.py
This PR makes QFieldCloud store and display the QGIS app version used by Jobs
**Note** : since the QGIS app version is stored in job's feedback, it will not be possible to get and display "old" jobs this way. Extracting it from Job's `Output pre` with a bit of regexp could be considered, if old job's QGIS version must be fetched anyway :
> Store and display jobs' qgis app version

- docker-app/qfieldcloud/settings.py
- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
Diff: https://github.com/jazzband/django-constance/compare/2.9.1...4.3.1
Old versions changelog: https://django-constance.readthedocs.io/en/latest/changes.html
New versions changelog: https://github.com/jazzband/django-constance/releases
4 django migrations have to be applied FYI
Note: the migrations introduced by dependency bumping are not reversible ([the 0003 one](https://github.com/jazzband/django-constance/compare/2.9.1...4.3.1#diff-a3c5f342d52fbe646e30d291705158eb3e3e8c8a3bf0c3019c58be94934f7787), using the new `constance` app instead of `database` before). Please take this information into consideration.
```
django.db.migrations.exceptions.IrreversibleError: Operation <RunPython <function migrate_pickled_data at 0x7f744f80d2d0>> in constance.0003_drop_pickle is not reversible
```
> [breaking] Bump `django-constance` from 2.9.1 to 4.3.1

- docker-app/qfieldcloud/core/utils2/audit.py
In older version of audit, the value must be a string. This is no longer the case and we have to push the value native type, usually a dict.
A manual patch of the database is needed, please run something like this:
```
update auditlog_logentry set changes = replace(replace(rtrim(ltrim(changes::text,'"'),'"'), '\"', '"'), '\\"', '')::jsonb where jsonb_typeof(changes) = 'string';
```
See https://app.clickup.com/t/2192114/QF-5019
> Fix manual write to audit, usually about file changes, that is a string

- docker-app/qfieldcloud/core/admin.py
I believe the Organization members and Teams are very related and makes sense to be next to each other.
|before|after|
|-|-|
| ![image](https://github.com/user-attachments/assets/cf688766-1ffd-4afb-b95a-8aa2b2d751ea) | ![image](https://github.com/user-attachments/assets/972f5bdc-cd75-4e3b-8275-e11b4fd27302) |
|before|after|
|-|-|
| ![image](https://github.com/user-attachments/assets/1f138915-7fba-4d71-916c-9ed9aa7a4842) | ![image](https://github.com/user-attachments/assets/6f956dfb-86d5-4bcc-8673-3080ac033463) |
> Reorder Organization admin tabs: members and teams should be neighbors

- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
Changelog: https://github.com/RealOrangeOne/django-sri/releases/tag/0.8.0
Diff: https://github.com/RealOrangeOne/django-sri/compare/0.7.0...0.8.0
> Bump `django-sri` from `0.7.0` to `0.8.0`

- docker-app/qfieldcloud/settings.py
Fixes:
```
?: settings.ACCOUNT_AUTHENTICATION_METHOD is deprecated, use: settings.ACCOUNT_LOGIN_METHODS = {'username', 'email'}
```
> Fix warning due to django-allauth update

- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
- docker-compose.override.standalone.yml
Changelog:
https://github.com/boto/boto3/blob/develop/CHANGELOG.rst
> Bump `boto3`, `boto3-stubs` and `mypy-boto3-s3` from 1.35.90 to 1.37.0 and `minio` to `RELEASE.2025-02-18T16-25-55Z`

- docker-app/qfieldcloud/settings.py
Hopefully should fix all the `KeyError` and `OSError` exceptions.
This is the recommended setting from Django, with some inflated value for the number of pool members.
See: https://docs.djangoproject.com/en/5.1/topics/cache/#cache-arguments
> Add some extra default settings to the cache configuration

- docker-app/qfieldcloud/core/middleware/requests.py
This PR resolves a TypeError that raised in attach_keys middleware when comparing `request.headers["Content-Length"]` (integer type) with `config.SENTRY_REQUEST_MAX_SIZE_TO_SEND` (string).
**Changes Implemented**
- Cast config.SENTRY_REQUEST_MAX_SIZE_TO_SEND to an integer before performing the comparison.
- Added error handling via defaulting max size to zero, if the value is invalid.
> [sentry] Fix comparison between of a constance setting and "Content-Length" header

- docker-app/qfieldcloud/settings.py
> Sign-up via invitation link process results in a broken `/accounts/profile` redirect

- docker-app/qfieldcloud/filestorage/management/commands/migratefilestorage.py
- docker-app/qfieldcloud/filestorage/management/commands/migrateprojectstorage.py
- docker-app/qfieldcloud/filestorage/migrate_project_storage.py
- docker-app/qfieldcloud/filestorage/migrations/0001_initial.py
- docker-app/qfieldcloud/filestorage/models.py
- docker-app/qfieldcloud/filestorage/utils.py
Basically the title, it seems besides minio version id that is a UUID , there are other providers that use other strings to represent version ids.
> Add the possibility to migrate file storage by exact username and support version ids that are not UUIDs

- .github/workflows/test.yml
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/utils.py
- docker-app/qfieldcloud/settings.py
- docker-compose.override.test.yml
Previously changing the default storage was only possible by modifying the STORAGES or during tests execution. Now one can change this also for regular web server execution via a envvar.
Also removed the deprecation of this feature being deleted with QF-4963.
> Make it easy to change the default storage by changing `STORAGES_PROJECT_DEFAULT_STORAGE`

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/utils.py
From 324 to 196 queries on the projects home screen.
> Make `Project.status` a cached property to drastically reduce the number of DB queries

- docker-app/qfieldcloud/filestorage/serializers.py
- docker-app/qfieldcloud/filestorage/tests/test_files_api.py
If we don't fix that, all the clients will assume that files has changed their checksum, while they did not.
> For historical reasons we named the `etag` as `md5sum` in the API

- docker-app/qfieldcloud/core/adapters.py
- docker-app/qfieldcloud/core/urls.py
- docker-app/qfieldcloud/core/views/accounts_views.py
This PR adds the email confirmation and resend logic to QFieldCloud, with a new url, a new view as well as overriding django allauth's `DefaultAccountAdapter`.
> Add mail confirmation and resend django logic

- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/filestorage/urls.py
- docker-app/qfieldcloud/filestorage/views.py
They expect that the avatar URL returned via API is always ending with a file extension, e.g. `.png`, `.svg` etc.
Now we do match this expectation by adding a new URL path:
```/files/avatars/<username>/avatar.<extension>/```
The `avatar.<extension>` does nothing, it is used just for the
backwards compatibility.
This is only used in the serializers.
> Fix backwards compatibility with QField/QFieldSync for avatars

- docker-app/qfieldcloud/filestorage/urls.py
Fix the fix in #1161 .
The error we target with this PR is:
> Remove trailing slash for avatars for backwards compatibility for QFieldSync

- docker-app/qfieldcloud/core/admin.py
- docker-app/qfieldcloud/core/migrations/0081_file_storage_project_and_more.py
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/filestorage/migrate_project_storage.py
What storage is being used and whether it is locked.
Added to project admin:
> Add information in the admin when the project has been migrated

- docker-app/qfieldcloud/core/fields.py
- docker-app/qfieldcloud/core/tests/test_admin.py
- docker-app/qfieldcloud/core/tests/test_useraccount.py
- docker-app/qfieldcloud/filestorage/models.py
- docker-app/qfieldcloud/filestorage/tests/test_files_api.py
- docker-app/qfieldcloud/settings.py
- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
Copy-paste from the docs https://github.com/un1t/django-cleanup:
> The django-cleanup app automatically deletes files for FileField, ImageField and subclasses. When a FileField's value is changed and the model is saved, the old file is deleted. When a model that has a FileField is deleted, the file is also deleted. A file that is set as the FileField's default value will not be deleted.
and
> In order to track changes of a FileField and facilitate file deletions, django-cleanup connects post_init, pre_save, post_save and post_delete signals to signal handlers for each INSTALLED_APPS model that has a FileField. In order to tell whether or not a FileField's value has changed a local cache of original values is kept on the model instance. If a condition is detected that should result in a …
> Delete the `FileField` files when a model entity is deleted

- .env.example
> Fix a misleading comment that the envvar is called `DYNAMIC_STORAGES`, but it we settled on `STORAGES` only

- docker-compose.yml
@suricactus seems when rebooting the server i.e. restarting docker daemon the memcached does not come up automatically on our infra and then the worker_wrapper hangs in restart loop
! This seems to help in our case at least but I let it up to you to check necessity for QFC classic
> Docker: Add memcached restart: unless-stopped policy

- docker-app/qfieldcloud/core/management/commands/dequeue.py
The observed error looks like this:
```
worker_wrapper-10  | {"ts":"12:26:43.487080","level":"INFO","name":"root","message":"Dequeued job de71eaa9-37c5-419c-a763-093b96904485, run!","filename":"dequeue.py","lineno":90,"thread":139638455768896,"source":"worker_wrapper"}
worker_wrapper-10  | {"ts":"12:26:43.500372","level":"WARNING","name":"worker_wrapper.wrapper","message":"Concurrent jobs occured for job ProcessProjectfileJob object (de71eaa9-37c5-419c-a763-093b96904485).","filename":"wrapper.py","lineno":136,"thread":139638455768896,"source":"worker_wrapper"}
worker_wrapper-1   | {"ts":"12:26:42.523750","level":"INFO","name":"root","message":"Dequeued job de71eaa9-37c5-419c-a763-093b96904485, run!","filename":"dequeue.py","lineno":90,"thread":140571515266880,"source":"worker_wrapper"} …
```
> Fixed wrong query in dequeue script leading to the same jobs being picked by multiple worker wrappers

- docker-app/qfieldcloud/core/serializers.py
This PR fixes the error encountered during autocomplete when adding teams as collaborators. The error “Team has no useraccount” occurred because the `get_avatar_url` method was attempting to access a non-existent `useraccount` attribute on team objects. The autocomplete endpoint (`/api/v1/users/?q=<search>&project=<project-id>`) returns both regular users and teams. Since teams do not have a useraccount, accessing it in the avatar URL helper was causing errors. This update ensures teams are correctly handled by simply returning `None` for their avatar URL.
Error Message: "Team has no useraccount."
**Changes**
- Added a type check to return `None` for avatar URLs when the object is a team (`user.type == user.Type.TEAM`), ensuring that teams no longer trigger an error by trying to access a …
> Fix: Do not require useraccount for teams during autocomplete

- .env.example
- docker-compose.override.standalone.yml
When upgrading my QFieldCloud instance I noticed, that `STORAGE_ACCESS_KEY_ID` and `STORAGE_SECRET_ACCESS_KEY` has been removed from `.env.example`. As this is fine for development it is required for the standalone config and should also stay in the config to be able to change the credentials.
It is not perfect, that the credentials are now redundant and also used in `STORAGES` but I don't see a solution for that. 
Thanks for your great work :)
> Add STORAGE_ACCESS_KEY_ID and STORAGE_SECRET_ACCESS_KEY to .env.example

- docker-app/qfieldcloud/subscription/admin.py
- docker-app/qfieldcloud/subscription/models.py
- docker-app/qfieldcloud/subscription/tests/test_subscription.py
This PR handles the issue raised when the admin creates an overlaping subscription. 
**Before**
Previously, the system allowed admin users to create subscriptions without checking for overlaps. This resulted in conflicting active subscriptions, leading to IntegrityErrors due to PostgreSQL's exclusion constraint (subscription_subscription_prevent_overlaps).
**After**
This PR introduces strict validation to prevent overlapping subscriptions before saving them in the admin panel. It prevents overlapping subscriptions by checking:
- If the new subscription’s active_since falls between an existing subscription’s active_since and active_until.
- if active_until is NULL (meaning the subscription is still ongoing), the new subscription cannot start.
- ~~Ensures only ACTIVE_PAID, ACTIVE_PAST_DUE, …
> Do not raise when subscription overlap in the admin

- docker-app/qfieldcloud/settings.py
The client sent invalid authentication token, the user should fix his token.
> Ignore `AuthenticationViaTokenFailedError` in sentry reports

- docker-app/qfieldcloud/core/middleware/qgis_auth.py
- docker-app/qfieldcloud/settings.py
This middleware allows to authenticate to QFC using **QGIS auth configs** with an **OpenID Connect** Authorization Code flow.
---
The reason this middleware is needed is as follows:
QGIS already has support for performing an OAuth2 Authorization Code flow using its authentication configs.
However, the way that QGIS passes the result of that flow (an access_token) to QFC is very limited, and cannot really be controlled. QGIS just runs the flow for the user, and then attaches the `access_token` it gets to any subsequent requests in the `Authorization` header.
However, `django-allauth`, for a regular web based OIDC flow, expects the final request of the flow to hit e.g. `/accounts/google/login/callback`, then will log the user in and create a session.
Because QGIS doesn't hit *any* …
> Add QGIS authentication middleware

- .env.example
- docker-app/qfieldcloud/core/utils.py
When hosted on AWS botocore automatically uses the IAM auth and env settings for S3, therefore no further env/settings need to be defined and passed to boto3 s3.
> Add S3 config for QFC on AWS hosts

- docker-app/qfieldcloud/core/views/package_views.py
- docker-app/qfieldcloud/filestorage/models.py
- docker-app/qfieldcloud/filestorage/view_helpers.py
Basiclly we need to filter not only by file type, name and version id, but when the file_type is PACKAGE, we also need to filter by package_job_id .
> Fix downloading package files from projects with multiple packages

- docker-app/qfieldcloud/authentication/tests/test_authentication.py
- docker-app/qfieldcloud/settings.py
This PR resolves an issue where Django Allauth was treating all usernames as lowercase during authentication, preventing users with capital letters in their usernames from logging in.
**The problem**
Usernames were correctly stored in the database with their original case (e.g., Bob), but authentication failed if users entered their names with uppercase letters.
**Solution**
Updated `ACCOUNT_PRESERVE_USERNAME_CASING` to `True` so to ensure usernames are not altered during authentication and are matched exactly as stored in the database.
**Impact**
- Users can now login using the their, exact case, username as stored in the db.
- No impact on existing stored usernames as only the authentication behavior has been adjusted.
**Test new functionality (Manual tests)**
- Tested logging in with …
> Fix case sensitivity issue in username handling

- docker-app/qfieldcloud/core/views/accounts_views.py
This PR fixes a potential assertion error raised when resending a confirmation email, in case the mail key is missing from the session.
> Fix potential assertion error when resending a confirmation email

- docker-app/qfieldcloud/filestorage/views.py
This PR addresses a bug where `kwargs.pop("thumbnail.png")` was mistakenly using a literal string as a key in projects where `legacy_storage` is used.
**Impact** 
Using the wrong key caused the function to raise a KeyError, breaking the thumbnail processing logic. This fix ensures the correct file is handled.
> Fix incorrect key usage in kwargs.pop() for filename extraction

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/worker_wrapper/wrapper.py
This PR makes QFC delete previous thumbnails versions of a project, when updating the project's thumbnail.
Thus avoiding multiple and important amount of s3 file versions for thumbnails, when versioning is enabled on a s3 storage.
> Delete previous thumbnails versions on s3 when updating project thumbnail

- .github/workflows/build_and_push.yml
Since the new QFieldCloud versioning has been setup, the build image are not tagged correctly using the version number, since those versions are not [semver](https://semver.org/) compliant.
Spotted in [this action run](https://github.com/opengisch/QFieldCloud/actions/runs/14118362595): ` Warning: v25.5 is not a valid semver. More info: https://semver.org/`.
It is possible to see the tagged version on dockerhub:
- before versioning change -> 0.32.5: present -> https://hub.docker.com/r/opengisch/qfieldcloud-app/tags?name=0.32.5
- now -> 25.5: empty -> https://hub.docker.com/r/opengisch/qfieldcloud-app/tags?name=25.5
The output of the [`docker-metadata` action](https://github.com/docker/metadata-action) needs to be fixed.
It is not possible to use [metadata's …
> [CI] Fix CI docker image build tagging on tag event

- docker-app/qfieldcloud/core/staticfiles/css/sso.css
- docker-app/qfieldcloud/core/templates/allauth/elements/provider.html
- docker-app/qfieldcloud/core/templates/socialaccount/snippets/provider_list.html
This PR customizes the display of the SSO providers buttons, in the login page.
Logic consists of overriding allauth's `provider.html` template, with style being configured in the `QFIELDCLOUD_SSO_PROVIDER_STYLES` settings variable (fill, stroke, text color + svg icon).
Since the QFieldCloud jazzmin UI is light, the `light` styles are being used at the moment.
Approach is to use a css file for non-dynamic style properties.
> Customize auth providers buttons by overriding allauth's template

- docker-app/qfieldcloud/core/models.py
This PR fixes the `thumbnail_url` value for projects using legacy storage.
Those projects don't have a `thumbnail` attribute value, so I guess the condition after the `or` was always true.
> Fix `thumbnail_url` for projects using legacy storage

- docker-createbuckets/Dockerfile
When upgrading my QFieldCloud instance, I noticed, that minio wasn't updated in the whole project. 
It is not an issue, but it is better to use the same version, I think.
But I think it would be great to update the base image.
Here are different things possible:
1. use python as base image
2. use python as base image and use minio library to get rid of the mc subprocesses
3. stay at ubuntu as is
Further, I noticed that there is also a newer version of minio, which I cloud also update. 
Please let me know which of the possibilities you would prefer and I can implement it.
Thanks for your great work :)
> Update minio createbuckets

- docker-app/qfieldcloud/core/templates/account/password_reset_from_key.html
- docker-app/qfieldcloud/core/templates/account/password_reset_from_key_done.html
This PR customizes the "reset password from key" page, by overriding allauth's `password_reset_from_key.html` and `password_reset_from_key_done.html` templates.
Such a page is generated an loads when opening a link generated with the `Generate reset password URL` action.
Before this PR, the page was not customized so the page looked like raw HTML.
| Before | After |
| - | - |
| ![image](https://github.com/user-attachments/assets/4a1d1dc8-5dea-4571-b94d-74410626ed98) | ![image](https://github.com/user-attachments/assets/f45c45fe-60a1-4b18-aa83-536ca71f9fe3) |
After having changed the password:
> Customize reset password from key page

- docker-app/qfieldcloud/authentication/auth_backends.py
- docker-app/qfieldcloud/core/drf_utils.py
- docker-app/qfieldcloud/core/invitations_utils.py
- docker-app/qfieldcloud/core/management/commands/deleteorphanedfiles.py
- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_jobs.py
- docker-app/qfieldcloud/core/utils.py
- docker-app/qfieldcloud/core/utils2/delta_utils.py
- docker-app/qfieldcloud/core/utils2/projects.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/core/views/accounts_views.py
- docker-app/qfieldcloud/filestorage/migrate_project_storage.py
- docker-app/qfieldcloud/filestorage/models.py
- docker-app/qfieldcloud/filestorage/utils.py
- docker-app/qfieldcloud/filestorage/view_helpers.py
- docker-app/qfieldcloud/filestorage/views.py
- docker-app/qfieldcloud/subscription/models.py
- docker-qgis/qfc_worker/apply_deltas.py
- docker-qgis/qfc_worker/process_projectfile.py
- docker-qgis/qfc_worker/utils.py
- scripts/check_envvars.py
We don't need to repeat ourselves with:
```
def foo(n: int):
"""
Args:
n (int): number
Returns:
(int): result
"""
```
As modern tools are fine with just:
```
def foo(n: int) -> int:
"""
Args:
n: number
Returns:
result
"""
```
> Remove types from docstrings, we can get them from PEP484 typing and retire `List` etc

- docker-app/Dockerfile
In theory I prefer having a pinned version, but we already have unpinned base images for other services, and I consider low this low risk when we are pinned to specific Python version.
Also took the opportunity to move the latest debian `bookworm`.
Fix https://github.com/opengisch/QFieldCloud/issues/1209
> Bump python to the latest 3.10 series and change from `buster` to `bookworm`

- .env.example
- README.md
- docker-compose.override.staging.yml
- docker-compose.override.standalone.yml
This PR makes the postgis docker version configurable in the environment file.
Reason behind this simplicity for bumping repository to new versions later, as well as more flexibility for local and standalone instances.
> Move postgis docker image version to environment

- docker-app/worker_wrapper/wrapper.py
- docker-qgis/qfc_worker/utils.py
Basically the title. The envvars defined as secrets were always intended to be passed to the worker. We finally do it.
> Fix user-defined environment variables not being passed to the QGIS worker

- .env.example
- .github/workflows/test.yml
- docker-app/qfieldcloud/core/tests/utils.py
- docker-app/qfieldcloud/core/utils2/storage.py
- docker-app/qfieldcloud/filestorage/backend.py
- docker-app/qfieldcloud/filestorage/tests/test_webdav.py
- docker-app/qfieldcloud/filestorage/view_helpers.py
- docker-app/qfieldcloud/settings_utils.py
- docker-compose.override.standalone.yml
- docker-createbuckets/createbuckets.py
- docker-nginx/templates/default.conf.template
This PR adds a Django storage backend for webdav, adapted and inspired [by this repository](https://github.com/marazmiki/django-webdav-storage).
Allows to use a new storage of type `qfieldcloud.filestorage.backend.QfcWebDAVStorage`, which implements basic methods for storing a project's files on it.
2 webdav server implementations tested:
- NextCloud's webdav.
- `bytemark/webdav` docker image (generic and basic webdav implementation), used for testing.
PR steps:
> Add webdav storage backend

- docker-app/qfieldcloud/core/views/projects_views.py
Turns out that there is a fake OPTIONS requests being processed, which sets the `view.action` to `None` instead of one of the known strings, e.g. the expected `list`.
Therefore we start returning `False` if the `view.action` is unknown as the most conservative approach.
NOTE most probably there are other list views that suffer from the same problem.
> Fix error 500 when using the DRF in-browser viewer on GET /projects

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/tests/test_localized_projects.py
- docker-app/qfieldcloud/core/tests/test_project.py
- docker-app/qfieldcloud/core/tests/testdata/simple_bumblebees_correct_localized.qgs
- docker-app/qfieldcloud/core/urls.py
- docker-app/qfieldcloud/core/views/projects_views.py
- docker-qgis/qfc_worker/utils.py
This PR introduces support for a new localized_datasets project, which serves as a centralized place to manage shared, localized files. This allows QFieldCloud users to reference common datasets across multiple projects without duplicating files. As a result, the updated logic ensures better synchronization, helps to avoid redundant uploads and provides QField with all the required information to efficiently access and fetch localized layers.
**Current Situation**
- The process_projectfile job only handled project files without checking for cross-project dependencies.
- Projects continued processing even when required datasets were missing.
**Actions to be implemented**
> Managing cross-project files (localized datasets)

- docker-compose.yml
"Expose" syntax is only a port number, not a port mapping. Exposes that port to the other docker containers running.
Otherwise it fails with `services.memcached.expose is invalid: should be of the format 'PORT[/PROTOCOL]'`.
However there is also a setting in the override files that exposes the port with a port mapping on the host machine:
```
memcached:
ports:
- "${MEMCACHED_PORT}:11211" # MEMCACHED_PORT is 11211 by default
```
So the question is should the port be exposed on the docker host machine or only to the other containers. I guess in a bigger setup it should be exposed on the host machine in case of distributed docker containers.
Maybe to be discussed before merging.
> Fix wrong syntax for docker-compose expose.

- docker-app/qfieldcloud/core/tests/mixins.py
- docker-app/qfieldcloud/core/tests/test_jobs.py
- docker-app/qfieldcloud/core/tests/test_localized_projects.py
- docker-app/qfieldcloud/core/tests/utils.py
- docker-app/qfieldcloud/filestorage/tests/test_files_api.py
- docker-app/qfieldcloud/filestorage/tests/test_webdav.py
This PR refactors the previous `QfcFilesTestCase` test class to a mixin, so that one can chose which `*TestCase` a test class should override.
> Refactor filestorage tests with files test mixin class

- docker-app/qfieldcloud/settings.py
Basically fixing this error: `django.template.exceptions.TemplateSyntaxError: 'bootstrap4' is not a registered tag library`.
> Add bootstrap to installed apps

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/tests/test_localized_projects.py
- docker-app/qfieldcloud/core/tests/test_project.py
Add a bit of extra info about the localized datasets and stick to double quotes in formatting.
> Do not show an error for missing localized dataset when it is available

- docker-app/qfieldcloud/core/exceptions.py
- docker-app/qfieldcloud/filestorage/tests/test_range.py
- docker-app/qfieldcloud/filestorage/utils.py
- docker-app/qfieldcloud/filestorage/view_helpers.py
- docker-app/qfieldcloud/settings.py
- docker-app/qfieldcloud/testing.py
- docker-nginx/templates/default.conf.template
This PR intends to allow downloading only a byte range of a file, using QFieldCloud API, by providing a `Range` HTTP header. Can be used if a big file's first download has crashed for some reason, this new header allows then to download only the missing bytes.
**cURL usage example**:
```sh
curl -X GET -L "https://my.qfieldcloud.server/api/v1/files/<PROJECT_ID>/<FILE_NAME>" \
-H "Authorization: Token <AUTH_TOKEN>" -H "Range: bytes=5-10"
```
**Examples of cURL HTTP headers that can be forwarded to the API, on the `/api/v1/files/<project_id>/<file_name>/` endpoint**:
- `-H "Range: bytes=2-7"` -> will download from byte number n°3 included to byte n°8 included.
- `-H "Range: bytes=3-"` -> will download from byte number n°4 included up to the last byte of the file.
**Steps**:
> Support `Range` in HTTP header during downloading files

- docker-nginx/templates/default.conf.template
For hosts that are not having ipv6 enabled we get an error. Unfortunately the resolver resolves to ipv6 by default.
> fix(nginx): disable ipv6 for the resolver in internal redirects for file download

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/tests/test_localized_projects.py
- docker-app/qfieldcloud/core/tests/test_project.py
Also rename the project name from `localized_datasets` to `shared_datasets`.
Improves the readability and explainability of the feature.
Note: there is a "breaking change" in the sense that `Project.localized_datasets_project_id` was renamed to `Project.shared_datasets_project_id` in the serializer, but the clients do not support this feature officially yet anyways, so it is acceptable.
> refactor(localized): rename all `localized_` prefixed variables to `shared_` regarding shared projects

- docker-createbuckets/createbuckets.py
The `mc config` command was deprecated for a while, and has finally been removed in the most recent version of the `mc` client: https://github.com/minio/mc/pull/5201
So instead of `mc config host add` we should use `mc alias set` (according to [MinIO Client docs](https://min.io/docs/minio/linux/reference/minio-mc.html#create-an-alias-for-the-s3-compatible-service))
This change should therefore prevent (at least one source of) headaches should we eventually want to upgrade the `mc` version in the `docker-createbuckets` Dockerfile in the future.
---
The most recent version of `mc` would fail like this for an attempt to use `mc config`:
```
createbuckets-1  | mc: <ERROR> `config` is not a recognized command. Get help using `--help` flag.
```
> createbuckets: Use mc alias set instead of mc config

- docker-app/qfieldcloud/settings.py
The client sent the wrong/unsupported HTTP `Range` header that we cannot satisfy, we cannot do much.
> fix(sentry): do not send reports about `InvalidRangeError` to sentry

- docker-app/qfieldcloud/filestorage/view_helpers.py
- docker-app/qfieldcloud/settings.py
The client attempted to upload a new .qgs/.qgz file, but the project already has one. The user must delete the QGIS file first before reuploading it.
> fix(sentry): do not send reports about `MultipleProjectsError` to sentry

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/filestorage/models.py
`Project.files` is returning both PROJECT_FILE and PACKAGE_FILE
This PR is a temporary fix with minimal diff.
> fix(filestorage): filter by file type when interacting with project files

- docker-app/qfieldcloud/core/filters.py
- docker-app/qfieldcloud/core/tests/test_project.py
- docker-app/qfieldcloud/core/urls.py
- docker-app/qfieldcloud/core/views/projects_views.py
@suricactus , as discussed, the PR adds two GET parameters to /api/v1/projects/ to filter the list by owner and/or project name. E.g., `/api/v1/projects/?owner=ivan&name=kebab`.
This will allow us to provide easier permalinks to retrieve cloud project details via API within QField.
> Add filtering capabilities to the /api/v1/projects/ endpoint to fetch project(s) details filtered by user name (and optionally a project name)

- docker-app/qfieldcloud/core/views/projects_views.py
Verified that there shouldn't be any performance issues as indices are used.
The search is performed as substring search after converting to UPPER().
See https://www.django-rest-framework.org/api-guide/filtering/#searchfilter
> feat(api): support search by project name or owner username in /projects

- docker-app/qfieldcloud/core/migrations/0084_project_is_attachment_download_on_demand.py
- docker-app/qfieldcloud/core/models.py
Trying to improve the wording a bit to ease understand. Using "should" instead of "may" to make it clear it's a behavior that will be enforced. I think we don't need the QField client bit, removing it makes for a shorter and clearer reading IMHO.
> Improve attachment on demand help description

- docker-app/qfieldcloud/core/models.py
- docker-qgis/entrypoint.py
- docker-qgis/qfc_worker/process_projectfile.py
Since we now have on-demand attachment download, using the attachment directories' trick to ship additional project assets (images used in symbology, print/atlas layouts, and decorators as well as files used by project plugin) has become unreliable. If a given project is set to on demand, the necessary assets will not be downloaded by QField.
A good solution is to stop abusing attachment directories and come up with a new directory type, which I've named 'data'. This is how it looks in QFieldSync when configuring directories:
_For the QFieldSync side of things, see https://github.com/opengisch/qfieldsync/pull/685_
@suricactus , as discussed over chat a while back.
> Introduce concept of data directories

- docker-app/qfieldcloud/core/models.py
- docker-app/qfieldcloud/core/tests/test_localized_projects.py
This PR resolved the issue with the warning about missing shared datasets in the project, even when the datasets were present and accessible.
**Scenario**
A project has been created in legacy storage mode
The dedicated `shared_datasets` project has been created in default storage mode
**Solution**
As the dedicated `shared_datasets` project is always created via default storage, all its files must be retrieved via the `file` model.
> Shared Datasets: do not warn about missing datasets when they do exist

- docker-app/qfieldcloud/core/serializers.py
- docker-app/qfieldcloud/core/tests/test_collaborators.py
- docker-app/qfieldcloud/core/views/collaborators_views.py
This PR solved the issue of adding a collaborator, which caused a KeyError as it was reading directly from request.data["collaborator"]. 
**Changes**
`ProjectCollaboratorSerializer` has been updated so that the collaborator field is now a writable `SlugRelatedField` instead of a read-only `StringRelatedField`.
> fix(core): switch collaborator field to SlugRelatedField using username

- docker-app/qfieldcloud/core/admin.py
Just noticed that the project admin page has a wrong description string for the file storage bytes field:
This PR fixes the situation.
> Fix file storage bytes help description in the project admin page

- docker-app/qfieldcloud/core/templates/admin/project_files_widget.html
Basically the title. Considering we'll always have a file version having the `is_latest` boolean flag to true.
> fix(files): make files widget download the latest version when no version is selected

- docker-app/qfieldcloud/filestorage/models.py
- docker-app/qfieldcloud/filestorage/tests/test_attachments.py
This PR ensures a FileVersion's target storage is the one of the related File.
> feat(storage): ensure a FileVersion's storage depends on the related file storage

- docker-app/qfieldcloud/filestorage/management/commands/migratefilestorage.py
- docker-app/qfieldcloud/filestorage/migrate_project_storage.py
This PR to study and optimize the file storage migration command for migrating projects storage.
Considering the projects stored on the `default` storage should not be migrated, this PR excludes them from ore-filtering based on CLI arguments.
> clean(storage): study and enhance filestorage migration command

- docker-app/qfieldcloud/core/tests/test_api.py
- docker-app/qfieldcloud/core/views/status_views.py
- docker-app/qfieldcloud/filestorage/backend.py
This PR adds a health-check status for every configured storage in the `/status` endpoint, as well as one for the database.
Before, the server was responding a json like : `{"geodb":"ok","storage":"ok"}`
This PR makes QFC respond a json like : `{"database": "ok", "storage": "ok"}`
- No more `geodb` check
- Each storage is checked based on its type (S3, webdav, etc.), one single `storage` key keeps being answered by the API.
> feat(status): add health check for database and configured storages

- docker-app/qfieldcloud/core/admin.py
Inline secrets in projects admin:
|-|-|
| <img width="1654" height="456" alt="image" src="https://github.com/user-attachments/assets/27b1f479-b4b8-40be-8d3b-315f6b73aed8" /> | <img width="1654" height="456" alt="image" src="https://github.com/user-attachments/assets/89ccf090-7171-4bc1-a2b4-fd5aa1ba0885" /> |
Same goes for the newly added inline secrets in organizations admin.
Standalone admin:
|-|-|
| <img width="1654" height="718" alt="image" src="https://github.com/user-attachments/assets/81725fc6-2021-405b-9417-c4a152516477" /> | <img width="1654" height="718" alt="image" src="https://github.com/user-attachments/assets/71d3c008-fedf-446b-b449-db7113fe58ed" /> |
> feat(admin): add assigned_to to inline project secrets

- docker-app/worker_wrapper/wrapper.py
- docker-qgis/qfc_worker/apply_deltas.py
This PR fixes https://github.com/opengisch/QFieldCloud/issues/570 , big thanks to @Joonalai for having been able to nail down replicable steps to trigger this delta apply failure scenario.
Basically, we had code in place to track source primary keys (PK) when applying multiple deltas within a client's downloaded package instance (i.e. clientId). However, that system did not take the local/source layer into account. 
Say QField pushed a delta pushed to QFC that modifies a feature on source layer A where the offlined feature PK (i.e. localPk) is 1. The generated key that maps modified source PKs would be "clientID__1".
The map now looks like this:
"clientID__1": modifiedPk 
Where the modifiedPk = the PK in the source layer A.
If you then push another delta (within the same downloaded …
> Fix last modified PK value match when modifying multiple offlined layers across multiple pushes

- docker-app/qfieldcloud/core/admin.py
search fields should not contain `organization__name__icontains`, but `organization__username__icontains`.
> fix(admin): searching for secrets admin throws error 500

- docker-app/qfieldcloud/filestorage/tests/test_range.py
- docker-app/qfieldcloud/settings.py
Also added a test that to check if `QFIELDCLOUD_MINIMUM_RANGE_HEADER_LENGTH>0` still works.
> feat(filestorage): disable the minimum bytes length in the HTTP Range header

- docker-app/qfieldcloud/settings.py
We cannot do much about it. Probably we can just monitor if there are way too many of them per hour or so in the monitoring.
> feat: do not report `TooManyLoginAttemptsError` to Sentry

- docker-app/qfieldcloud/core/tests/test_api.py
- docker-app/qfieldcloud/core/tests/test_status.py
- docker-app/qfieldcloud/core/views/status_views.py
- docker-app/qfieldcloud/settings.py
Added constance fields:
- STATUS_PAGE_URL - sets the status page
- INCIDENT_IS_ACTIVE - whether there is a known incident or not
- INCIDENT_TIMESTAMP_UTC - indicates when the incident started. We need
two separate fields with `INCIDENT_IS_ACTIVE` and
`INCIDENT_TIMESTAMP_UTC` because `constance` does not support the latter
to be nullable (it must be a datetime instance).
- INCIDENT_MESSAGE - message that can be shown to the users
Also some tests improvements: moved tests about the GET status API in a dedicated file and test the newly added fields `status_page_url`, `incident_timestamp_utc` and `incident_message`
Addings tests for the `database == error` field is hard, as one cannot simply
overwrite the `DATABASES` settings. Django prevents this with:
> Overriding setting DATABASES can lead …
> feat: added configuration to set incident info and status page url

- docker-app/qfieldcloud/authentication/admin.py
- docker-app/qfieldcloud/core/admin.py
The `Tokens` and `Groups` admins to be registered again in Django Admin :
> fix(admin): add unregistered admins

- docker-app/qfieldcloud/core/admin.py
Because we need to register it to the newly added `qfc_admin_site`.
> fix(admin): revive the django axes admin

- docker-app/qfieldcloud/filestorage/migrate_project_storage.py
A bit more verbosity during filestorage migration regarding how many package files there are to migrate for a project.
> edit(fsmigration): log count of migrated package files

- docker-app/requirements/requirements.in
- docker-app/requirements/requirements.txt
Changelog: https://docs.djangoproject.com/en/dev/releases/4.2.25/
Changes: https://github.com/django/django/compare/4.2.24...4.2.25
The bot in https://github.com/opengisch/QFieldCloud/pull/1374 is changing too many things.
> Bump `django` from `4.2.24` to `4.2.25`

- docker-app/qfieldcloud/subscription/migrations/0003_auto_20221028_1901.py
- docker-app/qfieldcloud/subscription/models.py
At some point storage_package `PackageType` was renamed to `storage` but the auto creation of it was never updated.
steps to reproduce
1. fresh install
2. `manage.py migrate`
3. created a super user `manage.py createsuperuser`
Now we see an extra package type which has `code = storage_package`, it caused issues when syncing with stripe and when deleting in admin panel
> Fix unnecessary creation of storage_package as `PackageType`
